(function(){
shadow$provide[0]=function(b,c,a,d){a.exports=React};
shadow$provide[1]=function(b,c,a,d){a.exports=ReactDOM};
'use strict';var z9=function(a,b){var c=Kna[a];if(void 0!==c)return c;try{x9.push(a);var d=y9[a],e=shadow$provide[a];if(void 0===d){if(void 0===e)throw"Module not provided: "+a;d={exports:{}};y9[a]=d}if(e){delete shadow$provide[a];try{e.call(d,$APP.aa,z9,d,d.exports)}catch(g){throw console.warn("shadow-cljs - failed to load",a),g;}if(b){var f=b.globals;if(f)for(a=0;a<f.length;a++)window[f[a]]=d.exports}}}finally{x9.pop()}return d.exports},A9=function(a){return 2>$APP.Te(a)?$APP.On(a):[$APP.On($APP.pl.j(a,
0,1)),$APP.pl.h(a,1)].join("")},C9=function(a){if("string"===typeof a)return a;a=$APP.$k(a);var b=$APP.Un.h(a,/-/),c=$APP.v(b);b=$APP.w(c);c=$APP.x(c);return $APP.l(B9.g?B9.g(b):B9.call(null,b))?a:$APP.Xh.j($APP.n,b,$APP.Al.h(A9,c))},D9=function(a){var b=function(){var c=function(){var d=$APP.jf(a);if(d){d=a.displayName;if($APP.l(d))return d;d=a.name;return"string"===typeof d&&$APP.v(d)?d:null}return d}();if($APP.l(c))return c;c=function(){var d=null!=a?a.R&4096||$APP.me===a.Ef?!0:!1:!1;return d?
$APP.$k(a):d}();if($APP.l(c))return c;c=$APP.nf(a);return $APP.xf(c)?$APP.S.g(c):null}();return $APP.l(b)?$APP.Mn($APP.n.g(b),"$","."):null},E9=function(a){return a instanceof $APP.qh||a instanceof $APP.t},F9=function(a){if($APP.xf(a))try{var b=$APP.Qf.h(a,$APP.AK)}catch(c){b=null}else b=null;return b},G9=function(a){var b=$APP.AK.g($APP.nf(a));if($APP.l(b))return b;b=F9($APP.y.j(a,1,null));if($APP.l(b))return b;b=$APP.y.j(a,0,null);switch(b instanceof $APP.qh?b.ca:null){case "\x3e":case "f\x3e":return F9($APP.y.j(a,
2,null));case "r\x3e":return a=$APP.y.j(a,2,null),null==a?null:a.key;default:return null}},H9=function(a){return setTimeout(a,16)},Lna=function(a,b){return a.Sf-b.Sf},I9=function(){return null},J9=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.A?d.A():d.call(null);c+=1}else return null},K9=function(a,b,c){b.push(c);return a.schedule()},L9=function(){this.bf=!1},N9=function(a){if($APP.l(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return M9.queue_render(a)},O9=function(a){if(null!=a&&null!=
a.di)a=a.id;else{var b=O9[$APP.ea(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=O9._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.uc("Compiler.get-id",a);}return a},P9=function(a,b){if(null!=a&&null!=a.gh)a=a.gh(a,b);else{var c=P9[$APP.ea(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=P9._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.uc("Compiler.as-element",a);}return a},Q9=function(a,b,c,d,e){if(null!=a&&null!=a.hh)a=a.hh(a,b,c,d,e);else{var f=
Q9[$APP.ea(null==a?null:a)];if(null!=f)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=Q9._,null!=f)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.uc("Compiler.make-element",a);}return a},S9=function(a,b){b.xf=null;a:{var c=R9;R9=b;try{var d=a.A?a.A():a.call(null);break a}finally{R9=c}d=void 0}a=b.xf;b.Vc=!1;a:{c=b.od;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var g=f===e;if(g){c=g;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);
return d},T9=function(a){var b=R9;if(null!=b){var c=b.xf;null==c?b.xf=[a]:c.push(a)}},U9=function(a,b,c){a.yb=$APP.H.j(a.yb,b,c);return a.sg=null},V9=function(a,b){a.yb=$APP.Jo.h(a.yb,b);return a.sg=null},W9=function(a,b,c){var d=a.sg;d=null==d?a.sg=$APP.jg(function(r,m,B){r.push(m);r.push(B);return r},[],a.yb):d;for(var e=d.length,f=0;;)if(f<e){var g=d[f],p=d[f+1];p.F?p.F(g,a,b,c):p.call(null,g,a,b,c);f=2+f}else break},X9=function(a,b,c,d){$APP.Ed(a,["#object[reagent.ratom.",$APP.n.g(c)," "].join(""));
a:{c=R9;R9=null;try{var e=d;break a}finally{R9=c}e=void 0}$APP.zl(e,a,b);return $APP.Ed(a,"]")},Y9=function(a,b,c,d){this.state=a;this.J=b;this.qg=c;this.yb=d;this.H=2154201088;this.R=114690},Z9=function(a){if(null!=a&&null!=a.kg)a=a.kg(a);else{var b=Z9[$APP.ea(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Z9._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.uc("IDisposable.dispose!",a);}return a},$9=function(a,b,c,d){return a._handle_change(b,c,d)},a$=function(a){this.f=a;
this.state=null;this.Vc=!0;this.$g=!1;this.yf=this.wc=this.yb=this.od=null;this.H=2153807872;this.R=114690},c$=function(){for(;;){var a=b$;if(null==a)return null;b$=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}},g$=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;c=arguments[0];var e=$APP.Zh(1<b.length?new $APP.se(b.slice(1),0,null):null);b=$APP.Qf.h(e,d$);d=$APP.Qf.h(e,e$);e=$APP.Qf.h(e,f$);c=new a$(c);c._set_opts(new $APP.k(null,
3,[d$,b,e$,d,f$,e],null));return c},i$=function(a,b){var c=Mna,d=h$,e=S9(a,d);null!=d.od&&(h$=g$(null),d._set_opts(c),d.f=a,d.wc=function(){return N9.g?N9.g(b):N9.call(null,b)},b.cljsRatom=d);return e},j$=function(a,b){var c=b.argv;if(null==c){c=$APP.E;a=a.constructor;a:for(var d=$APP.Xa(b),e=d.length,f=$APP.di,g=0;;)if(g<e){var p=d[g];f=$APP.H.j(f,$APP.Bl.g(p),$APP.bb(b,p));g+=1}else break a;b=new $APP.C(null,2,5,c,[a,f],null)}else b=c;return b},k$=function(a){var b;if(b=$APP.jf(a))a=null==a?null:
a.prototype,b=null!=(null==a?null:a.Yc);return b},Nna=function(a,b){for(;;){var c=a.Yc,d=!0===a.Lh?c.call(a,a):function(){var e=j$(a,a.props);switch($APP.Te(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.y.h(e,1));case 3:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2));case 4:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2),$APP.y.h(e,3));case 5:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2),$APP.y.h(e,3),$APP.y.h(e,4));default:return c.apply(a,$APP.TK.g(e).slice(1))}}();if($APP.zf(d))return P9(b,d);
if($APP.If(d))a.Yc=k$(d)?function(e,f,g,p,r){return function(){function m(D){var F=null;if(0<arguments.length){F=0;for(var M=Array(arguments.length-0);F<M.length;)M[F]=arguments[F+0],++F;F=new $APP.se(M,0,null)}return B.call(this,F)}function B(D){return P9(f,$APP.Xh.j($APP.tt,r,D))}m.v=0;m.B=function(D){D=$APP.v(D);return B(D)};m.l=B;return m}()}(a,b,c,null,d):d;else return d}},Ona=function(a,b){switch(a instanceof $APP.qh?a.ca:null){case "getDefaultProps":throw Error("getDefaultProps not supported");
case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.y.j(f,1,null),c=$APP.xf(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.Nh;d=null!=d?d:c.Nh=l$.g(null);return $APP.Fi(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,j$(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,this,j$(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,
this,j$(this,c))};case "shouldComponentUpdate":return function(c){var d=m$;if($APP.l(d))return d;d=this.props.argv;var e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.Qk.h(d,e)}catch(g){return!1}}else return f?b.call(this,this,j$(this,this.props),j$(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,j$(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,d){return b.call(this,this,j$(this,c),d)};case "componentDidUpdate":return function(c,
d,e){return b.call(this,this,j$(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.bb(this,"cljsRatom");null!=c&&Z9(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};case "componentDidCatch":return function(c,d){return b.call(this,this,c,d)};default:return null}},
Qna=function(a){return $APP.jg(function(b,c,d){return $APP.H.j(b,$APP.Bl.g(Pna(c)),d)},$APP.di,a)},Rna=function(a,b){var c=function(){var g=n$.g(a);return $APP.l(g)?g:o$.g(a)}(),d=null==n$.g(a),e=function(){var g=p$.g(a);if($APP.l(g))return g;g=D9(c);return $APP.l(g)?g:$APP.n.g($APP.Mo.g("reagent"))}(),f=$APP.jg(function(g,p,r){var m=$APP.H.j,B=Ona(p,r);return m.call($APP.H,g,p,$APP.l(B)?B:r)},$APP.di,a);return $APP.H.l(f,p$,e,$APP.Ye([q$,d,n$,c,o$,function(){var g=this,p=$APP.bb(g,"cljsRatom");g.cljsIsDirty=
!1;return null==p?i$(function(){a:{var r=r$;r$=g;try{var m=Nna(g,b);break a}finally{r$=r}m=void 0}return m},g):p._run(!1)}]))},s$=function(a){return $APP.jg(function(b,c,d){c=$APP.$k(c);b[c]=d;return b},{},a)},Tna=function(a,b){return Rna($APP.Io.l($APP.Ye([Sna,Qna(a)])),b)},x$=function(a,b){function c(p,r,m){t$.Component.call(this,p,r,m);$APP.l(g)&&(g.h?g.h(this,p):g.call(null,this,p));$APP.l(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.Sf=u$+=1;return this}a=Tna(a,b);b=s$($APP.Xh.l($APP.Jo,
a,p$,v$,$APP.Sq,$APP.Ye([o$,n$,w$])));var d=s$($APP.Rk(a,w$)),e=p$.g(a),f=v$.g(a),g=$APP.Sq.g(a);$APP.jb(c.prototype,t$.Component.prototype,b);$APP.l(o$.g(a))&&(c.prototype.render=o$.g(a));$APP.l(n$.g(a))&&(c.prototype.Yc=n$.g(a));$APP.l(q$.g(a))&&(c.prototype.Lh=q$.g(a));$APP.jb(c,t$.Component,d);$APP.l(e)&&(c.displayName=e,c.Dd=e,c.Qf=function(p){return $APP.Ed(p,e)});c.Qe=!0;return c.prototype.constructor=c},y$=function(a,b,c){a=O9(a);return b[a]=c},Una=function(a,b){for(;;){var c=b.Yc,d=b.argv,
e=$APP.Xh.h(c,d);if($APP.zf(e))return P9(a,e);if($APP.If(e))b.Yc=k$(e)?function(f,g,p,r,m,B){return function(){function D(M){var T=null;if(0<arguments.length){T=0;for(var ca=Array(arguments.length-0);T<ca.length;)ca[T]=arguments[T+0],++T;T=new $APP.se(ca,0,null)}return F.call(this,T)}function F(M){return P9(f,$APP.Xh.j($APP.tt,B,M))}D.v=0;D.B=function(M){M=$APP.v(M);return F(M)};D.l=F;return D}()}(a,b,c,null,d,e):e;else return e}},Vna=function(a,b){var c=b.argv,d=b.Yc;b=t$.useState(0);$APP.y.j(b,
0,null);var e=$APP.y.j(b,1,null),f=t$.useRef();$APP.l(f.current)||function(){var p={forceUpdate:function(){return e.g?e.g($APP.Fe):e.call(null,$APP.Fe)}};p.Sf=u$+=1;p.constructor=d;p.Yc=d;return f.current=p}();var g=f.current;b=$APP.bb(g,"cljsRatom");t$.useEffect(function(){return function(){var p=$APP.bb(g,"cljsRatom");return null==p?null:Z9(p)}},[]);g.argv=c;g.cljsIsDirty=!1;return null==b?i$(function(){a:{var p=r$;r$=g;try{var r=Una(a,g);break a}finally{r$=p}r=void 0}return r},g):b._run(!1)},Wna=
function(a,b){a=a.argv;b=b.argv;var c=!1===m$;if(c)try{return $APP.Ue.h(a,b)}catch(d){return!1}else return c},Xna=function(a,b){function c(e){return Vna(a,e)}var d=$APP.bb(b,O9(a));if($APP.l(d))return d;c.displayName=D9(b);d=t$.memo(c,Wna);y$(a,b,d);return d},$na=function(a,b,c,d){var e=$APP.Zh($APP.di);e=$APP.Qf.h(e,Yna);if(a===document.activeElement&&$APP.Sf(Zna,a.type)&&"string"===typeof b&&"string"===typeof c){var f=a.value;if($APP.Qk.h(f,c))return M9.add_after_render(function(){return z$.g?z$.g(d):
z$.call(null,d)});c=$APP.Te(f)-a.selectionStart;c=$APP.Te(b)-c;d.Re=b;a.value=b;$APP.jf(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.Re=b;a.value=b;return $APP.jf(e)?e.g?e.g(b):e.call(null,b):null},z$=function(a){if($APP.l(a.Rf)){a.Mg=!1;var b=a.Mh,c=a.Re,d=a.cg;return $APP.Qk.h(b,c)?$na(d,b,c,a):null}return null},aoa=function(a,b,c){a.Re=c.target.value;$APP.l(a.Mg)||(a.Mg=!0,M9.add_after_render(function(){return z$(a)}));return b.g?b.g(c):b.call(null,c)},boa=function(a){var b=
r$;if($APP.l(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.l(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.l(b.Rf)||(b.Rf=!0,b.Re=c);$APP.l(b.ih)||(b.ih=$APP.jf(e)?function(f){b.cg=f;return e.g?e.g(f):e.call(null,f)}:$APP.l($APP.l(e)?e.hasOwnProperty("current"):e)?function(f){b.cg=f;return e.current=f}:function(f){return b.cg=f});b.Mh=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return aoa(b,d,f)};a.ref=b.ih}},
A$=function(a,b){return a.hasOwnProperty(b)?$APP.bb(a,b):null},coa=function(a,b,c){if(E9(b)){var d=A$(B$,$APP.$k(b));null==d?(d=C9(b),b=$APP.$k(b),b=B$[b]=d):b=d}c=C$.g?C$.g(c):C$.call(null,c);a[b]=c;return a},C$=function(a){return"object"!==$APP.ea(a)?a:E9(a)?$APP.$k(a):$APP.xf(a)?$APP.jg(coa,{},a):$APP.sf(a)?$APP.Oq(a):$APP.If(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.se(f,0,null)}return c.call(this,
e)}function c(d){return $APP.Xh.h(a,d)}b.v=0;b.B=function(d){d=$APP.v(d);return c(d)};b.l=c;return b}():$APP.Oq(a)},doa=function(a,b,c){if(E9(b)){var d=A$(D$,$APP.$k(b));null==d?(d=C9(b),b=$APP.$k(b),b=D$[b]=d):b=d}c=C$(c);a[b]=c;return a},eoa=function(a){return"object"!==$APP.ea(a)?a:E9(a)?$APP.$k(a):$APP.xf(a)?$APP.jg(doa,{},a):$APP.sf(a)?$APP.Oq(a):$APP.If(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=
new $APP.se(f,0,null)}return c.call(this,e)}function c(d){return $APP.Xh.h(a,d)}b.v=0;b.B=function(d){d=$APP.v(d);return c(d)};b.l=c;return b}():$APP.Oq(a)},foa=function(a,b,c,d,e){switch($APP.Te(b)-e){case 0:return t$.createElement(c,d);case 1:return t$.createElement(c,d,P9(a,$APP.y.j(b,e,null)));default:return t$.createElement.apply(null,$APP.jg(function(f,g,p){g>=e&&f.push(P9(a,p));return f},[c,d],b))}},E$=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.Qh=d},G$=function(a,b,c){var d=
$APP.bb(a,O9(c));null==d?k$(a)?a=y$(c,a,a):(d=$APP.nf(a),d=$APP.H.j(d,F$,a),d=x$(d,c),a=y$(c,a,d)):a=d;c={};c.argv=b;b=G9(b);null!=b&&(c.key=b);return t$.createElement(a,c)},H$=function(a,b,c,d){var e={};e.Yc=a;e.argv=$APP.Sn.h(b,c);b=G9(b);null!=b&&(e.key=b);return t$.createElement(Xna(d,a),e)},goa=function(a,b,c){var d;if(d=$APP.jf(a))d=null==a?null:a.prototype,d=null!=(null==d?null:d.render);return d?G$(a,b,c):H$(a,b,1,c)},J$=function(a,b,c,d){var e=a.tag,f=$APP.y.j(b,c,null),g=null==f||$APP.xf(f),
p=function(){var m=g?f:null;var B=$APP.kr.g(m);B=$APP.l(B)?$APP.H.j(m,$APP.kr,I$.g(B)):m;var D=a.id;m=a.className;D=null!=D&&null==$APP.Zp.g(B)?$APP.H.j(B,$APP.Zp,D):B;if($APP.l(m)){var F=$APP.H.j,M=I$.h,T=$APP.kr.g(B);B=$APP.l(T)?T:hoa.g(B);m=F.call($APP.H,D,$APP.kr,M.call(I$,m,B))}else m=D;m=$APP.l(a.Qh)?eoa(m):C$(m);return $APP.l(m)?m:{}}();c+=g?1:0;a:switch(e){case "input":case "textarea":var r=!0;break a;default:r=!1}if(r)return r=function(){var m=d.ei;if($APP.l(m))return m;m=x$(ioa,d);return d.ei=
m}(),P9(d,$APP.mf(new $APP.C(null,6,5,$APP.E,[r,b,e,p,c,d],null),$APP.nf(b)));r=F9($APP.nf(b));null!=r&&(p.key=r);return Q9(d,b,e,p,c)},joa=function(a,b){return $APP.TK.g($APP.Al.h(function(c){return P9(b,c)},a))},loa=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.am.l($APP.Ye([a])));var d=$APP.y.j(a,0,null);switch(d instanceof $APP.qh?d.ca:null){case "\x3e":return c=$APP.y.j(a,1,null),J$(new E$(c,null,null,null),a,2,b);case "r\x3e":c=$APP.y.j(a,1,null);d=$APP.y.j(a,2,null);d=$APP.l(d)?
d:{};var e=F9($APP.nf(a));null!=e&&(d.key=e);return Q9(b,a,c,d,3);case "f\x3e":return H$($APP.y.j(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.y.j(a,1,null),c=null==d||$APP.xf(d),d=C$(c?d:null),d=$APP.l(d)?d:{},c=1+(c?1:0),e=G9(a),null!=e&&(d.key=e),Q9(b,a,t$.Fragment,d,c);default:if(E9(d)||"string"===typeof d)a:for(;;)switch(c=$APP.y.j(a,0,null),c=$APP.$k(c),d=c.indexOf("\x3e"),d){case -1:d=A$(K$,c);if(null==d){var f=$APP.x($APP.ll(koa,$APP.$k(c)));d=$APP.y.j(f,0,null);e=$APP.y.j(f,1,null);f=$APP.y.j(f,
2,null);f=null==f?null:$APP.Mn(f,/\./," ");var g=$APP.Qk.h(-1,d.indexOf("-"));d=new E$(d,e,f,g);c=K$[c]=d}else c=d;a=J$(c,a,1,b);break a;case 0:a=null;break a;default:a=$APP.mf(new $APP.C(null,2,5,$APP.E,[$APP.pl.j(c,0,d),$APP.H.j($APP.mf(a,null),0,$APP.pl.h(c,d+1))],null),$APP.nf(a))}else a=c.j?c.j(d,a,b):c.call(null,d,a,b);return a}},ooa=function(a,b,c){var d=m$;m$=!0;try{return moa.render(a.A?a.A():a.call(null),b,function(){var e=m$;m$=!1;try{return $APP.fm.F(noa,$APP.H,b,a),M9.flush_after_render(),
null!=c?c.A?c.A():c.call(null):null}finally{m$=e}})}finally{m$=d}},v$=new $APP.qh(null,"getInitialState","getInitialState",1541760916),poa=new $APP.qh(null,"component-will-unmount","component-will-unmount",-2058314698),n$=new $APP.qh(null,"reagentRender","reagentRender",-358306383),L$=new $APP.t(null,"container","container",-96406180,null),qoa=new $APP.t("reagent.core","as-element","reagent.core/as-element",-1369748434,null),roa=new $APP.qh(null,"contextType","contextType",1033066077),soa=new $APP.qh(null,
"getDerivedStateFromProps","getDerivedStateFromProps",-991834739),toa=new $APP.qh(null,"display-name","display-name",694513143),hoa=new $APP.qh(null,"className","className",-1983287057),uoa=new $APP.t("reagent.dom","render","reagent.dom/render",-1216356973,null),M$=new $APP.t(null,"callback-or-compiler","callback-or-compiler",90200066,null),N$=new $APP.t(null,"reagent.core","reagent.core",1841519592,null),O$=new $APP.t(null,"compiler","compiler",1372604796,null),f$=new $APP.qh(null,"on-dispose","on-dispose",
2105306360),P$=new $APP.qh(null,"no-cache","no-cache",1588056370),voa=new $APP.qh(null,"function-components","function-components",1492814963),Q$=new $APP.t(null,"reagent.dom","reagent.dom",-2138920962,null),woa=new $APP.qh(null,"callback","callback",-705136228),q$=new $APP.qh(null,"cljsLegacyRender","cljsLegacyRender",-1527295613),Yna=new $APP.qh(null,"on-write","on-write",31519475),xoa=new $APP.qh(null,"contextTypes","contextTypes",-2023853910),R$=new $APP.t(null,"render","render",232498073,null),
o$=new $APP.qh(null,"render","render",-1408033454),d$=new $APP.qh(null,"auto-run","auto-run",1958400437),yoa=new $APP.qh(null,"childContextTypes","childContextTypes",578717991),F$=new $APP.qh(null,"reagent-render","reagent-render",-985383853),zoa=new $APP.t("reagent.core","atom","reagent.core/atom",1748890217,null),Aoa=new $APP.qh(null,"componentWillUnmount","componentWillUnmount",1573788814),S$=new $APP.t(null,"as-element","as-element",-2139409597,null),p$=new $APP.qh(null,"displayName","displayName",
-809144601),Boa=new $APP.qh(null,"getDerivedStateFromError","getDerivedStateFromError",166658477),e$=new $APP.qh(null,"on-set","on-set",-140953470),Coa=new $APP.qh(null,"component-did-update","component-did-update",-1468549173),Doa=new $APP.qh(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);var y9={},Kna={},x9=[];z9.cache={};z9.resolve=function(a){return a};var t$=z9(0,{});var Eoa={};$APP.em.g(null);var Foa={},Goa="undefined"!==typeof window&&null!=window.document,B9=new $APP.Tk(null,new $APP.k(null,2,["aria",null,"data",null],null),null),I$=function I$(a){switch(arguments.length){case 0:return I$.A();case 1:return I$.g(arguments[0]);case 2:return I$.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return I$.l(arguments[0],arguments[1],new $APP.se(c.slice(2),0,null))}};I$.A=function(){return null};
I$.g=function(a){return $APP.sf(a)?(a=$APP.pz.h(function(b){return $APP.l(b)?E9(b)?$APP.$k(b):b:null},a),$APP.v(a)?$APP.xs.h(" ",a):null):E9(a)?$APP.$k(a):a};I$.h=function(a,b){return $APP.l(a)?$APP.l(b)?[$APP.n.g(I$.g(a))," ",$APP.n.g(I$.g(b))].join(""):I$.g(a):I$.g(b)};I$.l=function(a,b,c){return $APP.dg.j(I$,I$.h(a,b),c)};I$.B=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);c=$APP.x(c);return this.l(b,a,c)};I$.v=2;var m$=!1;var u$=0,T$=Goa?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.l(b))return b;b=a.webkitRequestAnimationFrame;if($APP.l(b))return b;b=a.mozRequestAnimationFrame;if($APP.l(b))return b;b=a.msRequestAnimationFrame;return $APP.l(b)?b:H9}().bind(a)}():H9;$APP.h=L9.prototype;$APP.h.flush_after_render=function(){var a=this.Ee;if(null==a)return null;this.Ee=null;return J9(a)};$APP.h.queue_render=function(a){null==this.Te&&(this.Te=[]);return K9(this,this.Te,a)};
$APP.h.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.bf)return null;this.bf=!0;return T$.g?T$.g(a):T$.call(null,a)};$APP.h.flush_before_flush=function(){var a=this.He;if(null==a)return null;this.He=null;return J9(a)};$APP.h.flush_queues=function(){this.flush_before_flush();I9();this.flush_render();return this.flush_after_render()};$APP.h.run_queues=function(){this.bf=!1;return this.flush_queues()};
$APP.h.add_before_flush=function(a){null==this.He&&(this.He=[]);return K9(this,this.He,a)};$APP.h.add_after_render=function(a){null==this.Ee&&(this.Ee=[]);return K9(this,this.Ee,a)};$APP.h.flush_render=function(){var a=this.Te;if(null==a)return null;this.Te=null;a:{a.sort(Lna);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};var M9=new L9;var R9;$APP.em.g(0);var b$=null;$APP.h=Y9.prototype;$APP.h.U=function(a,b,c){return X9(b,c,"RAtom",new $APP.k(null,1,[$APP.nM,this.rb(null)],null))};$APP.h.Y=function(){return this.J};$APP.h.X=function(){return $APP.ka(this)};$APP.h.P=function(a,b){return this===b};$APP.h.ac=function(a,b){a=this.state;this.state=b;null!=this.yb&&W9(this,a,b);return b};$APP.h.Kf=function(a,b){return this.ac(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.h.Lf=function(a,b,c){return this.ac(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.h.Mf=function(a,b,c,d){return this.ac(null,b.j?b.j(this.state,c,d):b.call(null,this.state,c,d))};$APP.h.Nf=function(a,b,c,d,e){return this.ac(null,$APP.Xh.N(b,this.state,c,d,e))};$APP.h.Pf=function(a,b){W9(this,a,b)};$APP.h.Ne=function(a,b,c){return U9(this,b,c)};$APP.h.Oe=function(a,b){return V9(this,b)};$APP.h.ba=function(a,b){return new Y9(this.state,b,this.qg,this.yb)};
$APP.h.rb=function(){T9(this);return this.state};var l$=function l$(a){switch(arguments.length){case 1:return l$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l$.l(arguments[0],new $APP.se(c.slice(1),0,null))}};l$.g=function(a){return new Y9(a,null,null,null)};l$.l=function(a,b){var c=$APP.Zh(b);b=$APP.Qf.h(c,$APP.$b);c=$APP.Qf.h(c,$APP.GL);return new Y9(a,b,c,null)};l$.B=function(a){var b=$APP.w(a);a=$APP.x(a);return this.l(b,a)};
l$.v=1;$APP.h=a$.prototype;$APP.h._peek_at=function(){var a=R9;R9=null;try{return this.rb(null)}finally{R9=a}};$APP.h._handle_change=function(a,b,c){return b===c||this.Vc?null:null==this.wc?(this.Vc=!0,null==b$&&(b$=[],!1===M9.bf&&M9.schedule()),b$.push(this)):!0===this.wc?this._run(!1):this.wc.g?this.wc.g(this):this.wc.call(null,this)};
$APP.h._update_watching=function(a){var b=$APP.Yk(a),c=$APP.Yk(this.od);this.od=a;a=$APP.v($APP.I6.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var g=d.W(null,f);$APP.Id(g,this,$9);f+=1}else if(a=$APP.v(a))d=a,$APP.Af(d)?(a=$APP.Td(d),f=$APP.Ud(d),d=a,e=$APP.Te(a),a=f):(a=$APP.w(d),$APP.Id(a,this,$9),a=$APP.x(d),d=null,e=0),f=0;else break;b=$APP.v($APP.I6.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.W(null,e),$APP.Jd(a,this),e+=1;else if(b=$APP.v(b))c=b,$APP.Af(c)?(b=$APP.Td(c),d=$APP.Ud(c),c=b,a=$APP.Te(b),
b=d,d=a):(a=$APP.w(c),$APP.Jd(a,this),b=$APP.x(c),c=null,d=0),e=0;else return null};$APP.h._queued_run=function(){return this.Vc&&null!=this.od?this._run(!0):null};$APP.h._try_capture=function(a){try{return this.yf=null,S9(a,this)}catch(b){return this.yf=this.state=a=b,this.Vc=!1}};$APP.h._run=function(a){var b=this.state;a=$APP.l(a)?this._try_capture(this.f):S9(this.f,this);this.$g||(this.state=a,null==this.yb||$APP.Ue.h(b,a)||W9(this,b,a));return a};
$APP.h._set_opts=function(a){var b=$APP.Zh(a);a=$APP.Qf.h(b,d$);var c=$APP.Qf.h(b,e$),d=$APP.Qf.h(b,f$);b=$APP.Qf.h(b,P$);null!=a&&(this.wc=a);null!=c&&(this.bi=c);null!=d&&(this.eh=d);return null!=b?this.$g=b:null};$APP.h.U=function(a,b,c){return X9(b,c,"Reaction",new $APP.k(null,1,[$APP.nM,this.rb(null)],null))};$APP.h.X=function(){return $APP.ka(this)};$APP.h.P=function(a,b){return this===b};
$APP.h.kg=function(){var a=this.state,b=this.od;this.wc=this.state=this.od=null;this.Vc=!0;b=$APP.v($APP.Yk(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.W(null,e);$APP.Jd(f,this);e+=1}else if(b=$APP.v(b))c=b,$APP.Af(c)?(b=$APP.Td(c),e=$APP.Ud(c),c=b,d=$APP.Te(b),b=e):(b=$APP.w(c),$APP.Jd(b,this),b=$APP.x(c),c=null,d=0),e=0;else break;null!=this.eh&&this.eh(a);a=this.Ji;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};
$APP.h.ac=function(a,b){a=this.state;this.state=b;this.bi(a,b);W9(this,a,b);return b};$APP.h.Kf=function(a,b){a=this.ac;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.h.Lf=function(a,b,c){a=this.ac;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.Mf=function(a,b,c,d){a=this.ac;var e=this._peek_at();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.h.Nf=function(a,b,c,d,e){return this.ac(null,$APP.Xh.N(b,this._peek_at(),c,d,e))};$APP.h.Pf=function(a,b){W9(this,a,b)};$APP.h.Ne=function(a,b,c){return U9(this,b,c)};$APP.h.Oe=function(a,b){a=$APP.rf(this.yb);V9(this,b);return!a&&$APP.rf(this.yb)&&null==this.wc?this.kg(null):null};
$APP.h.rb=function(){var a=this.yf;if(null!=a)throw a;(a=null==R9)&&(c$.A?c$.A():c$.call(null));a&&null==this.wc?this.Vc&&(a=this.state,this.state=this.f.A?this.f.A():this.f.call(null),null==this.yb||$APP.Ue.h(a,this.state)||W9(this,a,this.state)):(T9(this),this.Vc&&this._run(!1));return this.state};I9=c$;var h$=g$(null);var r$,Mna=new $APP.k(null,1,[P$,!0],null),Sna=new $APP.k(null,2,[Doa,null,Aoa,null],null),Pna=function(a){var b=$APP.em.g($APP.di);return function(c){var d=$APP.Qf.h($APP.hd(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.fm.F(b,$APP.H,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.$k(a);a=$APP.Mn(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.Un.h(a,/-/);var b=$APP.v(a);a=$APP.w(b);b=$APP.x(b);return $APP.Xh.j($APP.n,a,$APP.Al.h(A9,b))}),w$=new $APP.C(null,5,5,$APP.E,[yoa,
xoa,roa,soa,Boa],null);var Zna=new $APP.Tk(null,new $APP.k(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),ioa=new $APP.k(null,4,[toa,"ReagentInput",Coa,z$,poa,function(a){return a.Rf=null},F$,function(a,b,c,d,e){boa(c);return Q9(e,a,b,c,d)}],null);var Hoa={},U$,koa=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,B$={"class":"className","for":"htmlFor",charset:"charSet"},D$={},K$={},V$=function(a){var b=$APP.Mo.A(),c=$APP.l(voa.g(a))?goa:G$;if("undefined"===typeof Eoa||"undefined"===typeof Foa||"undefined"===typeof Hoa||"undefined"===typeof U$)U$=function(d,e,f,g){this.oc=d;this.id=e;this.Ug=f;this.Yh=g;this.H=393216;this.R=0},U$.prototype.ba=function(d,e){return new U$(this.oc,this.id,this.Ug,e)},U$.prototype.Y=function(){return this.Yh},U$.prototype.di=
function(){return this.id},U$.prototype.gh=function(d,e){return"object"!==$APP.ea(e)?e:$APP.zf(e)?loa(e,this,this.Ug):$APP.Ff(e)?joa(e,this):E9(e)?$APP.$k(e):(null!=e?e.H&2147483648||$APP.me===e.ha||(e.H?0:$APP.sc($APP.Fd,e)):$APP.sc($APP.Fd,e))?$APP.am.l($APP.Ye([e])):e},U$.prototype.hh=function(d,e,f,g,p){return foa(this,e,f,g,p)},U$.Qe=!0,U$.Dd="reagent.impl.template/t_reagent$impl$template37560",U$.Qf=function(d){return $APP.Ed(d,"reagent.impl.template/t_reagent$impl$template37560")};return new U$(a,
b,c,$APP.di)}($APP.di);var W$=function W$(a){switch(arguments.length){case 1:return W$.g(arguments[0]);case 2:return W$.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length)].join(""));}};W$.g=function(a){return P9(V$,a)};W$.h=function(a,b){return P9(b,a)};W$.v=2;
var X$=function X$(a){switch(arguments.length){case 1:return X$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X$.l(arguments[0],new $APP.se(c.slice(1),0,null))}};X$.g=function(a){return l$.g(a)};X$.l=function(a,b){return $APP.Xh.j(l$,a,b)};X$.B=function(a){var b=$APP.w(a);a=$APP.x(a);return this.l(b,a)};X$.v=1;var moa=z9(1,{});var noa=$APP.em.g($APP.di),Y$=function Y$(a){switch(arguments.length){case 2:return Y$.h(arguments[0],arguments[1]);case 3:return Y$.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length)].join(""));}};Y$.h=function(a,b){return Y$.j(a,b,V$)};
Y$.j=function(a,b,c){c$();c=$APP.jf(c)?new $APP.C(null,2,5,$APP.E,[V$,c],null):new $APP.C(null,2,5,$APP.E,[c,woa.g(c)],null);var d=$APP.y.j(c,0,null);c=$APP.y.j(c,1,null);return ooa(function(){return P9(d,$APP.jf(a)?a.A?a.A():a.call(null):a)},b,c)};Y$.v=3;var Z$=$APP.ep(N$,null),Ioa=new $APP.k(null,2,[$APP.fY,function(){var a=new $APP.u(function(){return X$},zoa,$APP.xk([$APP.V,$APP.S,$APP.Q,$APP.Nt,$APP.QS,$APP.O,$APP.K,$APP.Mt,$APP.X,$APP.Y,$APP.y_],[N$,$APP.fY,"reagent/core.cljs",11,new $APP.k(null,6,[$APP.C_,!0,$APP.Dr,1,$APP.hR,1,$APP.KR,new $APP.C(null,1,5,$APP.E,[new $APP.C(null,1,5,$APP.E,[$APP.wQ],null)],null),$APP.X,$APP.J(new $APP.C(null,1,5,$APP.E,[$APP.wQ],null),new $APP.C(null,3,5,$APP.E,[$APP.wQ,$APP.Ym,$APP.jZ],null)),$APP.WU,$APP.J(null,
null)],null),1,211,211,$APP.J(new $APP.C(null,1,5,$APP.E,[$APP.wQ],null),new $APP.C(null,3,5,$APP.E,[$APP.wQ,$APP.Ym,$APP.jZ],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.l(X$)?X$.o:null])),b=$APP.hd(a);a=$APP.nf(a);var c=Z$.s(null),d=$APP.S.g(a);$APP.I.h($APP.n.g(c),$APP.n.g(d));c=new $APP.k(null,4,[$APP.V,Z$,$APP.S,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.l($APP.up.g(a))?
$APP.JC(d,b,c):$APP.l($APP.Rp.g(a))?$APP.KC(d,b,c):new $APP.Cp(b,d,c)}(),S$,function(){var a=new $APP.u(function(){return W$},qoa,$APP.xk([$APP.V,$APP.S,$APP.Q,$APP.Nt,$APP.QS,$APP.O,$APP.K,$APP.Mt,$APP.X,$APP.Y,$APP.y_],[N$,S$,"reagent/core.cljs",17,new $APP.k(null,6,[$APP.C_,!1,$APP.Dr,2,$APP.hR,2,$APP.KR,new $APP.C(null,2,5,$APP.E,[new $APP.C(null,1,5,$APP.E,[$APP.I_],null),new $APP.C(null,2,5,$APP.E,[$APP.I_,O$],null)],null),$APP.X,$APP.J(new $APP.C(null,1,5,$APP.E,[$APP.I_],null),new $APP.C(null,
2,5,$APP.E,[$APP.I_,O$],null)),$APP.WU,$APP.J(null,null)],null),1,46,46,$APP.J(new $APP.C(null,1,5,$APP.E,[$APP.I_],null),new $APP.C(null,2,5,$APP.E,[$APP.I_,O$],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.l(W$)?W$.o:null])),b=$APP.hd(a);a=$APP.nf(a);var c=Z$.s(null),d=$APP.S.g(a);$APP.I.h($APP.n.g(c),$APP.n.g(d));c=new $APP.k(null,4,[$APP.V,Z$,$APP.S,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.l($APP.up.g(a))?
$APP.JC(d,b,c):$APP.l($APP.Rp.g(a))?$APP.KC(d,b,c):new $APP.Cp(b,d,c)}()],null),$$=$APP.ep(Q$,null),Joa=new $APP.k(null,1,[R$,function(){var a=new $APP.u(function(){return Y$},uoa,$APP.xk([$APP.V,$APP.S,$APP.Q,$APP.Nt,$APP.QS,$APP.O,$APP.K,$APP.Mt,$APP.X,$APP.Y,$APP.y_],[Q$,R$,"reagent/dom.cljs",13,new $APP.k(null,6,[$APP.C_,!1,$APP.Dr,3,$APP.hR,3,$APP.KR,new $APP.C(null,2,5,$APP.E,[new $APP.C(null,2,5,$APP.E,[$APP.b5,L$],null),new $APP.C(null,3,5,$APP.E,[$APP.b5,L$,M$],null)],null),$APP.X,$APP.J(new $APP.C(null,
2,5,$APP.E,[$APP.b5,L$],null),new $APP.C(null,3,5,$APP.E,[$APP.b5,L$,M$],null)),$APP.WU,$APP.J(null,null)],null),1,29,29,$APP.J(new $APP.C(null,2,5,$APP.E,[$APP.b5,L$],null),new $APP.C(null,3,5,$APP.E,[$APP.b5,L$,M$],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",
$APP.l(Y$)?Y$.o:null])),b=$APP.hd(a);a=$APP.nf(a);var c=$$.s(null),d=$APP.S.g(a);$APP.I.h($APP.n.g(c),$APP.n.g(d));c=new $APP.k(null,4,[$APP.V,$$,$APP.S,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.l($APP.up.g(a))?$APP.JC(d,b,c):$APP.l($APP.Rp.g(a))?$APP.KC(d,b,c):new $APP.Cp(b,d,c)}()],null);
$APP.fm.j($APP.eD,function(a,b){var c=$APP.Zh(b);b=$APP.Qf.h(c,$APP.hy);var d=$APP.Qf.h(c,$APP.hq),e=$APP.Qf.h(c,$APP.Up),f=$APP.Qf.h(c,$APP.xw),g=$APP.Qf.h(c,$APP.wY),p=$APP.Qf.h(c,$APP.yr),r=$APP.Qf.h(c,$APP.Xq),m=$APP.Qf.h(c,$APP.sr),B=$APP.Qf.h(c,$APP.ys),D=$APP.Qf.h(c,$APP.ns),F=$APP.Qf.h(c,$APP.ls),M=$APP.Qf.h(c,$APP.Vs),T=$APP.Qf.h(c,$APP.y4);c=$APP.Yp.g(a);$APP.DC(c,e,F,d,r,B);d=$APP.Io.l($APP.Ye([$APP.PY.g(a),T]));e=$APP.FC(d);r=$APP.H.l;B=$APP.Ku.g(a);return r.call($APP.H,new $APP.k(null,
5,[$APP.Up,$APP.di,$APP.Yp,c,$APP.hy,b,$APP.xw,f,$APP.Ku,$APP.l(B)?B:$APP.l(m)?m:M],null),$APP.sr,$APP.l(m)?$APP.EC($APP.sr.g(a),$APP.Ye([m])):null,$APP.Ye([$APP.Vs,$APP.l(M)?$APP.EC($APP.Vs.g(a),$APP.Ye([M])):null,$APP.ns,D,$APP.wY,g,$APP.yr,p,$APP.tr,$APP.tr.g(e),$APP.PY,d,$APP.Wq,$APP.Wq.g(e)]))},new $APP.k(null,1,[$APP.hq,new $APP.k(null,2,[N$,Ioa,Q$,Joa],null)],null));
}).call(this);