(function(){
shadow$provide[0]=function(b,c,a,d){a.exports=React};
shadow$provide[1]=function(b,c,a,d){a.exports=ReactDOM};
'use strict';var z9=function(a,b){var c=xda[a];if(void 0!==c)return c;try{x9.push(a);var d=y9[a],e=shadow$provide[a];if(void 0===d){if(void 0===e)throw"Module not provided: "+a;d={exports:{}};y9[a]=d}if(e){delete shadow$provide[a];try{e.call(d,$APP.aa,z9,d,d.exports)}catch(g){throw console.warn("shadow-cljs - failed to load",a),g;}if(b){var f=b.globals;if(f)for(a=0;a<f.length;a++)window[f[a]]=d.exports}}}finally{x9.pop()}return d.exports},A9=function(a){return 2>$APP.Zd(a)?$APP.Rm(a):[$APP.Rm($APP.tk.Vf(a,
0,1)),$APP.tk.h(a,1)].join("")},C9=function(a){if("string"===typeof a)return a;a=$APP.dk(a);var b=$APP.Xm.h(a,/-/),c=$APP.u(b);b=$APP.v(c);c=$APP.w(c);return $APP.l(B9.g?B9.g(b):B9.call(null,b))?a:$APP.ah.Vf($APP.n,b,$APP.Ek.h(A9,c))},D9=function(a){var b=function(){var c=function(){var d=$APP.pe(a);if(d){d=a.displayName;if($APP.l(d))return d;d=a.name;return"string"===typeof d&&$APP.u(d)?d:null}return d}();if($APP.l(c))return c;c=function(){var d=null!=a?a.K&4096||$APP.qd===a.Pd?!0:!1:!1;return d?
$APP.dk(a):d}();if($APP.l(c))return c;c=$APP.z(a);return $APP.Ae(c)?$APP.R.g(c):null}();return $APP.l(b)?$APP.Pm($APP.n.g(b),"$","."):null},E9=function(a){return a instanceof $APP.vg||a instanceof $APP.t},F9=function(a){if($APP.Ae(a))try{var b=$APP.Ue.h(a,$APP.LD)}catch(c){b=null}else b=null;return b},G9=function(a){var b=$APP.LD.g($APP.z(a));if($APP.l(b))return b;b=F9($APP.x.Vf(a,1,null));if($APP.l(b))return b;b=$APP.x.Vf(a,0,null);switch(b instanceof $APP.vg?b.fa:null){case "\x3e":case "f\x3e":return F9($APP.x.Vf(a,
2,null));case "r\x3e":return a=$APP.x.Vf(a,2,null),null==a?null:a.key;default:return null}},H9=function(a){return setTimeout(a,16)},yda=function(a,b){return a.de-b.de},I9=function(){return null},J9=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.s?d.s():d.call(null);c+=1}else return null},K9=function(a,b,c){b.push(c);return a.schedule()},L9=function(){this.Dd=!1},N9=function(a){if($APP.l(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return M9.queue_render(a)},O9=function(a){if(null!=a&&null!=
a.tf)a=a.id;else{var b=O9[$APP.ca(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=O9._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.hb("Compiler.get-id",a);}return a},P9=function(a,b){if(null!=a&&null!=a.Me)a=a.Me(a,b);else{var c=P9[$APP.ca(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=P9._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.hb("Compiler.as-element",a);}return a},Q9=function(a,b,c,d,e){if(null!=a&&null!=a.Ne)a=a.Ne(a,b,c,d,e);else{var f=
Q9[$APP.ca(null==a?null:a)];if(null!=f)a=f.H?f.H(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=Q9._,null!=f)a=f.H?f.H(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.hb("Compiler.make-element",a);}return a},S9=function(a,b){b.Jd=null;a:{var c=R9;R9=b;try{var d=a.s?a.s():a.call(null);break a}finally{R9=c}d=void 0}a=b.Jd;b.oc=!1;a:{c=b.zc;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var g=f===e;if(g){c=g;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);
return d},T9=function(a){var b=R9;if(null!=b){var c=b.Jd;null==c?b.Jd=[a]:c.push(a)}},U9=function(a,b,c){a.gb=$APP.H.Vf(a.gb,b,c);return a.ne=null},V9=function(a,b){a.gb=$APP.Mn.h(a.gb,b);return a.ne=null},W9=function(a,b,c){var d=a.ne;d=null==d?a.ne=$APP.lf(function(r,m,A){r.push(m);r.push(A);return r},[],a.gb):d;for(var e=d.length,f=0;;)if(f<e){var g=d[f],q=d[f+1];q.B?q.B(g,a,b,c):q.call(null,g,a,b,c);f=2+f}else break},X9=function(a,b,c,d){$APP.Gc(a,["#object[reagent.ratom.",$APP.n.g(c)," "].join(""));
a:{c=R9;R9=null;try{var e=d;break a}finally{R9=c}e=void 0}$APP.Dk(e,a,b);return $APP.Gc(a,"]")},Y9=function(a,b,c,d){this.state=a;this.D=b;this.me=c;this.gb=d;this.C=2154201088;this.K=114690},Z9=function(a){if(null!=a&&null!=a.ie)a=a.ie(a);else{var b=Z9[$APP.ca(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Z9._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.hb("IDisposable.dispose!",a);}return a},$9=function(a,b,c,d){return a._handle_change(b,c,d)},a$=function(a){this.f=a;
this.state=null;this.oc=!0;this.Ke=!1;this.Kd=this.Ob=this.gb=this.zc=null;this.C=2153807872;this.K=114690},c$=function(){for(;;){var a=b$;if(null==a)return null;b$=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}},g$=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;c=arguments[0];var e=$APP.ch(1<b.length?new $APP.yd(b.slice(1),0,null):null);b=$APP.Ue.h(e,d$);d=$APP.Ue.h(e,e$);e=$APP.Ue.h(e,f$);c=new a$(c);c._set_opts(new $APP.k(null,
3,[d$,b,e$,d,f$,e],null));return c},i$=function(a,b){var c=zda,d=h$,e=S9(a,d);null!=d.zc&&(h$=g$(null),d._set_opts(c),d.f=a,d.Ob=function(){return N9.g?N9.g(b):N9.call(null,b)},b.cljsRatom=d);return e},j$=function(a,b){var c=b.argv;if(null==c){c=$APP.G;a=a.constructor;a:for(var d=$APP.la(b),e=d.length,f=$APP.ih,g=0;;)if(g<e){var q=d[g];f=$APP.H.Vf(f,$APP.Fk.g(q),$APP.na(b,q));g+=1}else break a;b=new $APP.C(null,2,5,c,[a,f],null)}else b=c;return b},k$=function(a){var b;if(b=$APP.pe(a))a=null==a?null:
a.prototype,b=null!=(null==a?null:a.qc);return b},Ada=function(a,b){for(;;){var c=a.qc,d=!0===a.ff?c.call(a,a):function(){var e=j$(a,a.props);switch($APP.Zd(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.x.h(e,1));case 3:return c.call(a,$APP.x.h(e,1),$APP.x.h(e,2));case 4:return c.call(a,$APP.x.h(e,1),$APP.x.h(e,2),$APP.x.h(e,3));case 5:return c.call(a,$APP.x.h(e,1),$APP.x.h(e,2),$APP.x.h(e,3),$APP.x.h(e,4));default:return c.apply(a,$APP.bE.g(e).slice(1))}}();if($APP.Ce(d))return P9(b,d);
if($APP.Me(d))a.qc=k$(d)?function(e,f,g,q,r){return function(){function m(D){var E=null;if(0<arguments.length){E=0;for(var M=Array(arguments.length-0);E<M.length;)M[E]=arguments[E+0],++E;E=new $APP.yd(M,0,null)}return A.call(this,E)}function A(D){return P9(f,$APP.ah.Vf($APP.ys,r,D))}m.o=0;m.Xf=function(D){D=$APP.u(D);return A(D)};m.j=A;return m}()}(a,b,c,null,d):d;else return d}},Bda=function(a,b){switch(a instanceof $APP.vg?a.fa:null){case "getDefaultProps":throw Error("getDefaultProps not supported");
case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.x.Vf(f,1,null),c=$APP.Ae(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.hf;d=null!=d?d:c.hf=l$.g(null);return $APP.Gh(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,j$(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,this,j$(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,
this,j$(this,c))};case "shouldComponentUpdate":return function(c){var d=m$;if($APP.l(d))return d;d=this.props.argv;var e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.Tj.h(d,e)}catch(g){return!1}}else return f?b.call(this,this,j$(this,this.props),j$(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,j$(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,d){return b.call(this,this,j$(this,c),d)};case "componentDidUpdate":return function(c,
d,e){return b.call(this,this,j$(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.na(this,"cljsRatom");null!=c&&Z9(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};case "componentDidCatch":return function(c,d){return b.call(this,this,c,d)};default:return null}},
Dda=function(a){return $APP.lf(function(b,c,d){return $APP.H.Vf(b,$APP.Fk.g(Cda(c)),d)},$APP.ih,a)},Eda=function(a,b){var c=function(){var g=n$.g(a);return $APP.l(g)?g:o$.g(a)}(),d=null==n$.g(a),e=function(){var g=p$.g(a);if($APP.l(g))return g;g=D9(c);return $APP.l(g)?g:$APP.n.g($APP.Pn.g("reagent"))}(),f=$APP.lf(function(g,q,r){var m=$APP.H.Vf,A=Bda(q,r);return m.call($APP.H,g,q,$APP.l(A)?A:r)},$APP.ih,a);return $APP.H.j(f,p$,e,$APP.ee([q$,d,n$,c,o$,function(){var g=this,q=$APP.na(g,"cljsRatom");
g.cljsIsDirty=!1;return null==q?i$(function(){a:{var r=r$;r$=g;try{var m=Ada(g,b);break a}finally{r$=r}m=void 0}return m},g):q._run(!1)}]))},s$=function(a){return $APP.lf(function(b,c,d){c=$APP.dk(c);b[c]=d;return b},{},a)},Gda=function(a,b){return Eda($APP.Ln.j($APP.ee([Fda,Dda(a)])),b)},x$=function(a,b){function c(q,r,m){t$.Component.call(this,q,r,m);$APP.l(g)&&(g.h?g.h(this,q):g.call(null,this,q));$APP.l(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.de=u$+=1;return this}a=Gda(a,b);b=s$($APP.ah.j($APP.Mn,
a,p$,v$,$APP.Zp,$APP.ee([o$,n$,w$])));var d=s$($APP.Uj(a,w$)),e=p$.g(a),f=v$.g(a),g=$APP.Zp.g(a);$APP.w9(c.prototype,t$.Component.prototype,b);$APP.l(o$.g(a))&&(c.prototype.render=o$.g(a));$APP.l(n$.g(a))&&(c.prototype.qc=n$.g(a));$APP.l(q$.g(a))&&(c.prototype.ff=q$.g(a));$APP.w9(c,t$.Component,d);$APP.l(e)&&(c.displayName=e,c.Jc=e,c.be=function(q){return $APP.Gc(q,e)});c.yd=!0;return c.prototype.constructor=c},y$=function(a,b,c){a=O9(a);return b[a]=c},Hda=function(a,b){for(;;){var c=b.qc,d=b.argv,
e=$APP.ah.h(c,d);if($APP.Ce(e))return P9(a,e);if($APP.Me(e))b.qc=k$(e)?function(f,g,q,r,m,A){return function(){function D(M){var T=null;if(0<arguments.length){T=0;for(var Y=Array(arguments.length-0);T<Y.length;)Y[T]=arguments[T+0],++T;T=new $APP.yd(Y,0,null)}return E.call(this,T)}function E(M){return P9(f,$APP.ah.Vf($APP.ys,A,M))}D.o=0;D.Xf=function(M){M=$APP.u(M);return E(M)};D.j=E;return D}()}(a,b,c,null,d,e):e;else return e}},Ida=function(a,b){var c=b.argv,d=b.qc;b=t$.useState(0);$APP.x.Vf(b,0,
null);var e=$APP.x.Vf(b,1,null),f=t$.useRef();$APP.l(f.current)||function(){var q={forceUpdate:function(){return e.g?e.g($APP.Kd):e.call(null,$APP.Kd)}};q.de=u$+=1;q.constructor=d;q.qc=d;return f.current=q}();var g=f.current;b=$APP.na(g,"cljsRatom");t$.useEffect(function(){return function(){var q=$APP.na(g,"cljsRatom");return null==q?null:Z9(q)}},[]);g.argv=c;g.cljsIsDirty=!1;return null==b?i$(function(){a:{var q=r$;r$=g;try{var r=Hda(a,g);break a}finally{r$=q}r=void 0}return r},g):b._run(!1)},Jda=
function(a,b){a=a.argv;b=b.argv;var c=!1===m$;if(c)try{return $APP.ae.h(a,b)}catch(d){return!1}else return c},Kda=function(a,b){function c(e){return Ida(a,e)}var d=$APP.na(b,O9(a));if($APP.l(d))return d;c.displayName=D9(b);d=t$.memo(c,Jda);y$(a,b,d);return d},Nda=function(a,b,c,d){var e=$APP.ch($APP.ih);e=$APP.Ue.h(e,Lda);if(a===document.activeElement&&$APP.We(Mda,a.type)&&"string"===typeof b&&"string"===typeof c){var f=a.value;if($APP.Tj.h(f,c))return M9.add_after_render(function(){return z$.g?z$.g(d):
z$.call(null,d)});c=$APP.Zd(f)-a.selectionStart;c=$APP.Zd(b)-c;d.zd=b;a.value=b;$APP.pe(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.zd=b;a.value=b;return $APP.pe(e)?e.g?e.g(b):e.call(null,b):null},z$=function(a){if($APP.l(a.ce)){a.De=!1;var b=a.gf,c=a.zd,d=a.fe;return $APP.Tj.h(b,c)?Nda(d,b,c,a):null}return null},Oda=function(a,b,c){a.zd=c.target.value;$APP.l(a.De)||(a.De=!0,M9.add_after_render(function(){return z$(a)}));return b.g?b.g(c):b.call(null,c)},Pda=function(a){var b=
r$;if($APP.l(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.l(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.l(b.ce)||(b.ce=!0,b.zd=c);$APP.l(b.Oe)||(b.Oe=$APP.pe(e)?function(f){b.fe=f;return e.g?e.g(f):e.call(null,f)}:$APP.l($APP.l(e)?e.hasOwnProperty("current"):e)?function(f){b.fe=f;return e.current=f}:function(f){return b.fe=f});b.gf=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return Oda(b,d,f)};a.ref=b.Oe}},
A$=function(a,b){return a.hasOwnProperty(b)?$APP.na(a,b):null},Qda=function(a,b,c){if(E9(b)){var d=A$(B$,$APP.dk(b));null==d?(d=C9(b),b=$APP.dk(b),b=B$[b]=d):b=d}c=C$.g?C$.g(c):C$.call(null,c);a[b]=c;return a},C$=function(a){return"object"!==$APP.ca(a)?a:E9(a)?$APP.dk(a):$APP.Ae(a)?$APP.lf(Qda,{},a):$APP.ve(a)?$APP.Vp(a):$APP.Me(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.yd(f,0,null)}return c.call(this,
e)}function c(d){return $APP.ah.h(a,d)}b.o=0;b.Xf=function(d){d=$APP.u(d);return c(d)};b.j=c;return b}():$APP.Vp(a)},Rda=function(a,b,c){if(E9(b)){var d=A$(D$,$APP.dk(b));null==d?(d=C9(b),b=$APP.dk(b),b=D$[b]=d):b=d}c=C$(c);a[b]=c;return a},Sda=function(a){return"object"!==$APP.ca(a)?a:E9(a)?$APP.dk(a):$APP.Ae(a)?$APP.lf(Rda,{},a):$APP.ve(a)?$APP.Vp(a):$APP.Me(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;
e=new $APP.yd(f,0,null)}return c.call(this,e)}function c(d){return $APP.ah.h(a,d)}b.o=0;b.Xf=function(d){d=$APP.u(d);return c(d)};b.j=c;return b}():$APP.Vp(a)},Tda=function(a,b,c,d,e){switch($APP.Zd(b)-e){case 0:return t$.createElement(c,d);case 1:return t$.createElement(c,d,P9(a,$APP.x.Vf(b,e,null)));default:return t$.createElement.apply(null,$APP.lf(function(f,g,q){g>=e&&f.push(P9(a,q));return f},[c,d],b))}},E$=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.jf=d},G$=function(a,b,c){var d=
$APP.na(a,O9(c));null==d?k$(a)?a=y$(c,a,a):(d=$APP.z(a),d=$APP.H.Vf(d,F$,a),d=x$(d,c),a=y$(c,a,d)):a=d;c={};c.argv=b;b=G9(b);null!=b&&(c.key=b);return t$.createElement(a,c)},H$=function(a,b,c,d){var e={};e.qc=a;e.argv=$APP.Vm.h(b,c);b=G9(b);null!=b&&(e.key=b);return t$.createElement(Kda(d,a),e)},Uda=function(a,b,c){var d;if(d=$APP.pe(a))d=null==a?null:a.prototype,d=null!=(null==d?null:d.render);return d?G$(a,b,c):H$(a,b,1,c)},J$=function(a,b,c,d){var e=a.tag,f=$APP.x.Vf(b,c,null),g=null==f||$APP.Ae(f),
q=function(){var m=g?f:null;var A=$APP.rq.g(m);A=$APP.l(A)?$APP.H.Vf(m,$APP.rq,I$.g(A)):m;var D=a.id;m=a.className;D=null!=D&&null==$APP.dp.g(A)?$APP.H.Vf(A,$APP.dp,D):A;if($APP.l(m)){var E=$APP.H.Vf,M=I$.h,T=$APP.rq.g(A);A=$APP.l(T)?T:Vda.g(A);m=E.call($APP.H,D,$APP.rq,M.call(I$,m,A))}else m=D;m=$APP.l(a.jf)?Sda(m):C$(m);return $APP.l(m)?m:{}}();c+=g?1:0;a:switch(e){case "input":case "textarea":var r=!0;break a;default:r=!1}if(r)return r=function(){var m=d.uf;if($APP.l(m))return m;m=x$(Wda,d);return d.uf=
m}(),P9(d,$APP.re(new $APP.C(null,6,5,$APP.G,[r,b,e,q,c,d],null),$APP.z(b)));r=F9($APP.z(b));null!=r&&(q.key=r);return Q9(d,b,e,q,c)},Xda=function(a,b){return $APP.bE.g($APP.Ek.h(function(c){return P9(b,c)},a))},Zda=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.el.j($APP.ee([a])));var d=$APP.x.Vf(a,0,null);switch(d instanceof $APP.vg?d.fa:null){case "\x3e":return c=$APP.x.Vf(a,1,null),J$(new E$(c,null,null,null),a,2,b);case "r\x3e":c=$APP.x.Vf(a,1,null);d=$APP.x.Vf(a,2,null);d=$APP.l(d)?
d:{};var e=F9($APP.z(a));null!=e&&(d.key=e);return Q9(b,a,c,d,3);case "f\x3e":return H$($APP.x.Vf(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.x.Vf(a,1,null),c=null==d||$APP.Ae(d),d=C$(c?d:null),d=$APP.l(d)?d:{},c=1+(c?1:0),e=G9(a),null!=e&&(d.key=e),Q9(b,a,t$.Fragment,d,c);default:if(E9(d)||"string"===typeof d)a:for(;;)switch(c=$APP.x.Vf(a,0,null),c=$APP.dk(c),d=c.indexOf("\x3e"),d){case -1:d=A$(K$,c);if(null==d){var f=$APP.w($APP.pk(Yda,$APP.dk(c)));d=$APP.x.Vf(f,0,null);e=$APP.x.Vf(f,1,null);
f=$APP.x.Vf(f,2,null);f=null==f?null:$APP.Pm(f,/\./," ");var g=$APP.Tj.h(-1,d.indexOf("-"));d=new E$(d,e,f,g);c=K$[c]=d}else c=d;a=J$(c,a,1,b);break a;case 0:a=null;break a;default:a=$APP.re(new $APP.C(null,2,5,$APP.G,[$APP.tk.Vf(c,0,d),$APP.H.Vf($APP.re(a,null),0,$APP.tk.h(c,d+1))],null),$APP.z(a))}else a=c.Vf?c.Vf(d,a,b):c.call(null,d,a,b);return a}},bea=function(a,b,c){var d=m$;m$=!0;try{return $da.render(a.s?a.s():a.call(null),b,function(){var e=m$;m$=!1;try{return $APP.jl.B(aea,$APP.H,b,a),M9.flush_after_render(),
null!=c?c.s?c.s():c.call(null):null}finally{m$=e}})}finally{m$=d}},v$=new $APP.vg(null,"getInitialState","getInitialState",1541760916),cea=new $APP.vg(null,"component-will-unmount","component-will-unmount",-2058314698),n$=new $APP.vg(null,"reagentRender","reagentRender",-358306383),L$=new $APP.t(null,"container","container",-96406180,null),dea=new $APP.t("reagent.core","as-element","reagent.core/as-element",-1369748434,null),eea=new $APP.vg(null,"contextType","contextType",1033066077),fea=new $APP.vg(null,
"getDerivedStateFromProps","getDerivedStateFromProps",-991834739),gea=new $APP.vg(null,"display-name","display-name",694513143),Vda=new $APP.vg(null,"className","className",-1983287057),hea=new $APP.t("reagent.dom","render","reagent.dom/render",-1216356973,null),M$=new $APP.t(null,"callback-or-compiler","callback-or-compiler",90200066,null),N$=new $APP.t(null,"reagent.core","reagent.core",1841519592,null),O$=new $APP.t(null,"compiler","compiler",1372604796,null),f$=new $APP.vg(null,"on-dispose","on-dispose",
2105306360),P$=new $APP.vg(null,"no-cache","no-cache",1588056370),iea=new $APP.vg(null,"function-components","function-components",1492814963),Q$=new $APP.t(null,"reagent.dom","reagent.dom",-2138920962,null),jea=new $APP.vg(null,"callback","callback",-705136228),q$=new $APP.vg(null,"cljsLegacyRender","cljsLegacyRender",-1527295613),Lda=new $APP.vg(null,"on-write","on-write",31519475),kea=new $APP.vg(null,"contextTypes","contextTypes",-2023853910),R$=new $APP.t(null,"render","render",232498073,null),
o$=new $APP.vg(null,"render","render",-1408033454),d$=new $APP.vg(null,"auto-run","auto-run",1958400437),lea=new $APP.vg(null,"childContextTypes","childContextTypes",578717991),F$=new $APP.vg(null,"reagent-render","reagent-render",-985383853),mea=new $APP.t("reagent.core","atom","reagent.core/atom",1748890217,null),nea=new $APP.vg(null,"componentWillUnmount","componentWillUnmount",1573788814),S$=new $APP.t(null,"as-element","as-element",-2139409597,null),p$=new $APP.vg(null,"displayName","displayName",
-809144601),oea=new $APP.vg(null,"getDerivedStateFromError","getDerivedStateFromError",166658477),e$=new $APP.vg(null,"on-set","on-set",-140953470),pea=new $APP.vg(null,"component-did-update","component-did-update",-1468549173),qea=new $APP.vg(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);var y9={},xda={},x9=[];z9.cache={};z9.resolve=function(a){return a};var t$=z9(0,{});var rea={};$APP.il.g(null);var sea={},tea="undefined"!==typeof window&&null!=window.document,B9=new $APP.Wj(null,new $APP.k(null,2,["aria",null,"data",null],null),null),I$=function I$(a){switch(arguments.length){case 0:return I$.s();case 1:return I$.g(arguments[0]);case 2:return I$.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return I$.j(arguments[0],arguments[1],new $APP.yd(c.slice(2),0,null))}};I$.s=function(){return null};
I$.g=function(a){return $APP.ve(a)?(a=$APP.qB.h(function(b){return $APP.l(b)?E9(b)?$APP.dk(b):b:null},a),$APP.u(a)?$APP.Cr.h(" ",a):null):E9(a)?$APP.dk(a):a};I$.h=function(a,b){return $APP.l(a)?$APP.l(b)?[$APP.n.g(I$.g(a))," ",$APP.n.g(I$.g(b))].join(""):I$.g(a):I$.g(b)};I$.j=function(a,b,c){return $APP.ef.Vf(I$,I$.h(a,b),c)};I$.Xf=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.j(b,a,c)};I$.o=2;var m$=!1;var u$=0,T$=tea?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.l(b))return b;b=a.webkitRequestAnimationFrame;if($APP.l(b))return b;b=a.mozRequestAnimationFrame;if($APP.l(b))return b;b=a.msRequestAnimationFrame;return $APP.l(b)?b:H9}().bind(a)}():H9;$APP.h=L9.prototype;$APP.h.flush_after_render=function(){var a=this.pd;if(null==a)return null;this.pd=null;return J9(a)};$APP.h.queue_render=function(a){null==this.Bd&&(this.Bd=[]);return K9(this,this.Bd,a)};
$APP.h.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.Dd)return null;this.Dd=!0;return T$.g?T$.g(a):T$.call(null,a)};$APP.h.flush_before_flush=function(){var a=this.qd;if(null==a)return null;this.qd=null;return J9(a)};$APP.h.flush_queues=function(){this.flush_before_flush();I9();this.flush_render();return this.flush_after_render()};$APP.h.run_queues=function(){this.Dd=!1;return this.flush_queues()};
$APP.h.add_before_flush=function(a){null==this.qd&&(this.qd=[]);return K9(this,this.qd,a)};$APP.h.add_after_render=function(a){null==this.pd&&(this.pd=[]);return K9(this,this.pd,a)};$APP.h.flush_render=function(){var a=this.Bd;if(null==a)return null;this.Bd=null;a:{a.sort(yda);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};var M9=new L9;var R9;$APP.il.g(0);var b$=null;$APP.h=Y9.prototype;$APP.h.R=function(a,b,c){return X9(b,c,"RAtom",new $APP.k(null,1,[$APP.wF,this.ab(null)],null))};$APP.h.U=function(){return this.D};$APP.h.W=function(){return $APP.fa(this)};$APP.h.S=function(a,b){return this===b};$APP.h.Cb=function(a,b){a=this.state;this.state=b;null!=this.gb&&W9(this,a,b);return b};$APP.h.Vd=function(a,b){return this.Cb(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.h.Wd=function(a,b,c){return this.Cb(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.h.Xd=function(a,b,c,d){return this.Cb(null,b.Vf?b.Vf(this.state,c,d):b.call(null,this.state,c,d))};$APP.h.Yd=function(a,b,c,d,e){return this.Cb(null,$APP.ah.H(b,this.state,c,d,e))};$APP.h.$d=function(a,b){W9(this,a,b)};$APP.h.wd=function(a,b,c){return U9(this,b,c)};$APP.h.xd=function(a,b){return V9(this,b)};$APP.h.Y=function(a,b){return new Y9(this.state,b,this.me,this.gb)};
$APP.h.ab=function(){T9(this);return this.state};var l$=function l$(a){switch(arguments.length){case 1:return l$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l$.j(arguments[0],new $APP.yd(c.slice(1),0,null))}};l$.g=function(a){return new Y9(a,null,null,null)};l$.j=function(a,b){var c=$APP.ch(b);b=$APP.Ue.h(c,$APP.xa);c=$APP.Ue.h(c,$APP.PE);return new Y9(a,b,c,null)};l$.Xf=function(a){var b=$APP.v(a);a=$APP.w(a);return this.j(b,a)};
l$.o=1;$APP.h=a$.prototype;$APP.h._peek_at=function(){var a=R9;R9=null;try{return this.ab(null)}finally{R9=a}};$APP.h._handle_change=function(a,b,c){return b===c||this.oc?null:null==this.Ob?(this.oc=!0,null==b$&&(b$=[],!1===M9.Dd&&M9.schedule()),b$.push(this)):!0===this.Ob?this._run(!1):this.Ob.g?this.Ob.g(this):this.Ob.call(null,this)};
$APP.h._update_watching=function(a){var b=$APP.bk(a),c=$APP.bk(this.zc);this.zc=a;a=$APP.u($APP.s7.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var g=d.T(null,f);$APP.Lc(g,this,$9);f+=1}else if(a=$APP.u(a))d=a,$APP.De(d)?(a=$APP.Xc(d),f=$APP.Yc(d),d=a,e=$APP.Zd(a),a=f):(a=$APP.v(d),$APP.Lc(a,this,$9),a=$APP.w(d),d=null,e=0),f=0;else break;b=$APP.u($APP.s7.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.T(null,e),$APP.Mc(a,this),e+=1;else if(b=$APP.u(b))c=b,$APP.De(c)?(b=$APP.Xc(c),d=$APP.Yc(c),c=b,a=$APP.Zd(b),
b=d,d=a):(a=$APP.v(c),$APP.Mc(a,this),b=$APP.w(c),c=null,d=0),e=0;else return null};$APP.h._queued_run=function(){return this.oc&&null!=this.zc?this._run(!0):null};$APP.h._try_capture=function(a){try{return this.Kd=null,S9(a,this)}catch(b){return this.Kd=this.state=a=b,this.oc=!1}};$APP.h._run=function(a){var b=this.state;a=$APP.l(a)?this._try_capture(this.f):S9(this.f,this);this.Ke||(this.state=a,null==this.gb||$APP.ae.h(b,a)||W9(this,b,a));return a};
$APP.h._set_opts=function(a){var b=$APP.ch(a);a=$APP.Ue.h(b,d$);var c=$APP.Ue.h(b,e$),d=$APP.Ue.h(b,f$);b=$APP.Ue.h(b,P$);null!=a&&(this.Ob=a);null!=c&&(this.qf=c);null!=d&&(this.Le=d);return null!=b?this.Ke=b:null};$APP.h.R=function(a,b,c){return X9(b,c,"Reaction",new $APP.k(null,1,[$APP.wF,this.ab(null)],null))};$APP.h.W=function(){return $APP.fa(this)};$APP.h.S=function(a,b){return this===b};
$APP.h.ie=function(){var a=this.state,b=this.zc;this.Ob=this.state=this.zc=null;this.oc=!0;b=$APP.u($APP.bk(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.T(null,e);$APP.Mc(f,this);e+=1}else if(b=$APP.u(b))c=b,$APP.De(c)?(b=$APP.Xc(c),e=$APP.Yc(c),c=b,d=$APP.Zd(b),b=e):(b=$APP.v(c),$APP.Mc(b,this),b=$APP.w(c),c=null,d=0),e=0;else break;null!=this.Le&&this.Le(a);a=this.Tf;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};
$APP.h.Cb=function(a,b){a=this.state;this.state=b;this.qf(a,b);W9(this,a,b);return b};$APP.h.Vd=function(a,b){a=this.Cb;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.h.Wd=function(a,b,c){a=this.Cb;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.Xd=function(a,b,c,d){a=this.Cb;var e=this._peek_at();b=b.Vf?b.Vf(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.h.Yd=function(a,b,c,d,e){return this.Cb(null,$APP.ah.H(b,this._peek_at(),c,d,e))};$APP.h.$d=function(a,b){W9(this,a,b)};$APP.h.wd=function(a,b,c){return U9(this,b,c)};$APP.h.xd=function(a,b){a=$APP.ue(this.gb);V9(this,b);return!a&&$APP.ue(this.gb)&&null==this.Ob?this.ie(null):null};
$APP.h.ab=function(){var a=this.Kd;if(null!=a)throw a;(a=null==R9)&&(c$.s?c$.s():c$.call(null));a&&null==this.Ob?this.oc&&(a=this.state,this.state=this.f.s?this.f.s():this.f.call(null),null==this.gb||$APP.ae.h(a,this.state)||W9(this,a,this.state)):(T9(this),this.oc&&this._run(!1));return this.state};I9=c$;var h$=g$(null);var r$,zda=new $APP.k(null,1,[P$,!0],null),Fda=new $APP.k(null,2,[qea,null,nea,null],null),Cda=function(a){var b=$APP.il.g($APP.ih);return function(c){var d=$APP.Ue.h($APP.jc(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.jl.B(b,$APP.H,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.dk(a);a=$APP.Pm(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.Xm.h(a,/-/);var b=$APP.u(a);a=$APP.v(b);b=$APP.w(b);return $APP.ah.Vf($APP.n,a,$APP.Ek.h(A9,b))}),w$=new $APP.C(null,5,5,$APP.G,
[lea,kea,eea,fea,oea],null);var Mda=new $APP.Wj(null,new $APP.k(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),Wda=new $APP.k(null,4,[gea,"ReagentInput",pea,z$,cea,function(a){return a.ce=null},F$,function(a,b,c,d,e){Pda(c);return Q9(e,a,b,c,d)}],null);var uea={},U$,Yda=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,B$={"class":"className","for":"htmlFor",charset:"charSet"},D$={},K$={},V$=function(a){var b=$APP.Pn.s(),c=$APP.l(iea.g(a))?Uda:G$;if("undefined"===typeof rea||"undefined"===typeof sea||"undefined"===typeof uea||"undefined"===typeof U$)U$=function(d,e,f,g){this.rf=d;this.id=e;this.He=f;this.nf=g;this.C=393216;this.K=0},U$.prototype.Y=function(d,e){return new U$(this.rf,this.id,this.He,e)},U$.prototype.U=function(){return this.nf},U$.prototype.tf=
function(){return this.id},U$.prototype.Me=function(d,e){return"object"!==$APP.ca(e)?e:$APP.Ce(e)?Zda(e,this,this.He):$APP.Ie(e)?Xda(e,this):E9(e)?$APP.dk(e):(null!=e?e.C&2147483648||$APP.qd===e.ca||(e.C?0:$APP.cb($APP.Ic,e)):$APP.cb($APP.Ic,e))?$APP.el.j($APP.ee([e])):e},U$.prototype.Ne=function(d,e,f,g,q){return Tda(this,e,f,g,q)},U$.yd=!0,U$.Jc="reagent.impl.template/t_reagent$impl$template36031",U$.be=function(d){return $APP.Gc(d,"reagent.impl.template/t_reagent$impl$template36031")};return new U$(a,
b,c,$APP.ih)}($APP.ih);var W$=function W$(a){switch(arguments.length){case 1:return W$.g(arguments[0]);case 2:return W$.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length)].join(""));}};W$.g=function(a){return P9(V$,a)};W$.h=function(a,b){return P9(b,a)};W$.o=2;
var X$=function X$(a){switch(arguments.length){case 1:return X$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X$.j(arguments[0],new $APP.yd(c.slice(1),0,null))}};X$.g=function(a){return l$.g(a)};X$.j=function(a,b){return $APP.ah.Vf(l$,a,b)};X$.Xf=function(a){var b=$APP.v(a);a=$APP.w(a);return this.j(b,a)};X$.o=1;var $da=z9(1,{});var aea=$APP.il.g($APP.ih),Y$=function Y$(a){switch(arguments.length){case 2:return Y$.h(arguments[0],arguments[1]);case 3:return Y$.Vf(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length)].join(""));}};Y$.h=function(a,b){return Y$.Vf(a,b,V$)};
Y$.Vf=function(a,b,c){c$();c=$APP.pe(c)?new $APP.C(null,2,5,$APP.G,[V$,c],null):new $APP.C(null,2,5,$APP.G,[c,jea.g(c)],null);var d=$APP.x.Vf(c,0,null);c=$APP.x.Vf(c,1,null);return bea(function(){return P9(d,$APP.pe(a)?a.s?a.s():a.call(null):a)},b,c)};Y$.o=3;var Z$=$APP.ko(N$,null),vea=new $APP.k(null,2,[$APP.hZ,function(){var a=new $APP.vd(function(){return X$},mea,$APP.Aj([$APP.S,$APP.R,$APP.O,$APP.Ss,$APP.xL,$APP.Ro,$APP.K,$APP.Rs,$APP.W,$APP.X,$APP.R2],[N$,$APP.hZ,"reagent/core.cljs",11,new $APP.k(null,6,[$APP.W2,!0,$APP.Kq,1,$APP.RJ,1,$APP.qK,new $APP.C(null,1,5,$APP.G,[new $APP.C(null,1,5,$APP.G,[$APP.jJ],null)],null),$APP.W,$APP.J(new $APP.C(null,1,5,$APP.G,[$APP.jJ],null),new $APP.C(null,3,5,$APP.G,[$APP.jJ,$APP.bm,$APP.u0],null)),$APP.aP,$APP.J(null,
null)],null),1,211,211,$APP.J(new $APP.C(null,1,5,$APP.G,[$APP.jJ],null),new $APP.C(null,3,5,$APP.G,[$APP.jJ,$APP.bm,$APP.u0],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.l(X$)?X$.l:null])),b=$APP.jc(a);a=$APP.z(a);var c=Z$.Wf(null),d=$APP.R.g(a);$APP.I.h($APP.n.g(c),$APP.n.g(d));c=new $APP.k(null,4,[$APP.S,Z$,$APP.R,d,$APP.W,$APP.W.g(a),$APP.X,$APP.X.g(a)],null);return $APP.l($APP.yo.g(a))?
$APP.OB(d,b,c):$APP.l($APP.Wo.g(a))?$APP.PB(d,b,c):new $APP.Go(b,d,c)}(),S$,function(){var a=new $APP.vd(function(){return W$},dea,$APP.Aj([$APP.S,$APP.R,$APP.O,$APP.Ss,$APP.xL,$APP.Ro,$APP.K,$APP.Rs,$APP.W,$APP.X,$APP.R2],[N$,S$,"reagent/core.cljs",17,new $APP.k(null,6,[$APP.W2,!1,$APP.Kq,2,$APP.RJ,2,$APP.qK,new $APP.C(null,2,5,$APP.G,[new $APP.C(null,1,5,$APP.G,[$APP.d3],null),new $APP.C(null,2,5,$APP.G,[$APP.d3,O$],null)],null),$APP.W,$APP.J(new $APP.C(null,1,5,$APP.G,[$APP.d3],null),new $APP.C(null,
2,5,$APP.G,[$APP.d3,O$],null)),$APP.aP,$APP.J(null,null)],null),1,46,46,$APP.J(new $APP.C(null,1,5,$APP.G,[$APP.d3],null),new $APP.C(null,2,5,$APP.G,[$APP.d3,O$],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.l(W$)?W$.l:null])),b=$APP.jc(a);a=$APP.z(a);var c=Z$.Wf(null),d=$APP.R.g(a);$APP.I.h($APP.n.g(c),$APP.n.g(d));c=new $APP.k(null,4,[$APP.S,Z$,$APP.R,d,$APP.W,$APP.W.g(a),$APP.X,$APP.X.g(a)],null);return $APP.l($APP.yo.g(a))?
$APP.OB(d,b,c):$APP.l($APP.Wo.g(a))?$APP.PB(d,b,c):new $APP.Go(b,d,c)}()],null),$$=$APP.ko(Q$,null),wea=new $APP.k(null,1,[R$,function(){var a=new $APP.vd(function(){return Y$},hea,$APP.Aj([$APP.S,$APP.R,$APP.O,$APP.Ss,$APP.xL,$APP.Ro,$APP.K,$APP.Rs,$APP.W,$APP.X,$APP.R2],[Q$,R$,"reagent/dom.cljs",13,new $APP.k(null,6,[$APP.W2,!1,$APP.Kq,3,$APP.RJ,3,$APP.qK,new $APP.C(null,2,5,$APP.G,[new $APP.C(null,2,5,$APP.G,[$APP.c5,L$],null),new $APP.C(null,3,5,$APP.G,[$APP.c5,L$,M$],null)],null),$APP.W,$APP.J(new $APP.C(null,
2,5,$APP.G,[$APP.c5,L$],null),new $APP.C(null,3,5,$APP.G,[$APP.c5,L$,M$],null)),$APP.aP,$APP.J(null,null)],null),1,29,29,$APP.J(new $APP.C(null,2,5,$APP.G,[$APP.c5,L$],null),new $APP.C(null,3,5,$APP.G,[$APP.c5,L$,M$],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",
$APP.l(Y$)?Y$.l:null])),b=$APP.jc(a);a=$APP.z(a);var c=$$.Wf(null),d=$APP.R.g(a);$APP.I.h($APP.n.g(c),$APP.n.g(d));c=new $APP.k(null,4,[$APP.S,$$,$APP.R,d,$APP.W,$APP.W.g(a),$APP.X,$APP.X.g(a)],null);return $APP.l($APP.yo.g(a))?$APP.OB(d,b,c):$APP.l($APP.Wo.g(a))?$APP.PB(d,b,c):new $APP.Go(b,d,c)}()],null);
$APP.jl.Vf($APP.jC,function(a,b){var c=$APP.ch(b);b=$APP.Ue.h(c,$APP.iA);var d=$APP.Ue.h(c,$APP.mp),e=$APP.Ue.h(c,$APP.Zo),f=$APP.Ue.h(c,$APP.Fv),g=$APP.Ue.h(c,$APP.PZ),q=$APP.Ue.h(c,$APP.Fq),r=$APP.Ue.h(c,$APP.dq),m=$APP.Ue.h(c,$APP.zq),A=$APP.Ue.h(c,$APP.Dr),D=$APP.Ue.h(c,$APP.sr),E=$APP.Ue.h(c,$APP.qr),M=$APP.Ue.h(c,$APP.$r),T=$APP.Ue.h(c,$APP.i4);c=$APP.cp.g(a);$APP.IB(c,e,E,d,r,A);d=$APP.Ln.j($APP.ee([$APP.C_.g(a),T]));e=$APP.KB(d);r=$APP.H.j;A=$APP.Pt.g(a);return r.call($APP.H,new $APP.k(null,
5,[$APP.Zo,$APP.ih,$APP.cp,c,$APP.iA,b,$APP.Fv,f,$APP.Pt,$APP.l(A)?A:$APP.l(m)?m:M],null),$APP.zq,$APP.l(m)?$APP.JB($APP.zq.g(a),$APP.ee([m])):null,$APP.ee([$APP.$r,$APP.l(M)?$APP.JB($APP.$r.g(a),$APP.ee([M])):null,$APP.sr,D,$APP.PZ,g,$APP.Fq,q,$APP.Aq,$APP.Aq.g(e),$APP.C_,d,$APP.cq,$APP.cq.g(e)]))},new $APP.k(null,1,[$APP.mp,new $APP.k(null,2,[N$,vea,Q$,wea],null)],null));
}).call(this);