(function(){
shadow$provide[1]=function(b,c,a,d){a.exports=ReactDOM};
'use strict';var pma=function(a,b,c){var d=$APP.NF;$APP.NF=!0;try{return nma.render(a.o?a.o():a.call(null),b,function(){var e=$APP.NF;$APP.NF=!1;try{return $APP.nl.v(oma,$APP.G,b,a),$APP.bF.flush_after_render(),null!=c?c.o?c.o():c.call(null):null}finally{$APP.NF=e}})}finally{$APP.NF=d}},V$=new $APP.q(null,"container","container",-96406180,null),qma=new $APP.q("reagent.dom","render","reagent.dom/render",-1216356973,null),W$=new $APP.q(null,"callback-or-compiler","callback-or-compiler",90200066,null),
X$=new $APP.q(null,"reagent.dom","reagent.dom",-2138920962,null),rma=new $APP.wg(null,"callback","callback",-705136228);var nma=$APP.JE(1,{});var oma=$APP.ml.g($APP.jh),Y$=function Y$(a){switch(arguments.length){case 2:return Y$.h(arguments[0],arguments[1]);case 3:return Y$.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};Y$.h=function(a,b){return Y$.i(a,b,$APP.gH)};
Y$.i=function(a,b,c){$APP.zF();c=$APP.qe(c)?new $APP.D(null,2,5,$APP.E,[$APP.gH,c],null):new $APP.D(null,2,5,$APP.E,[c,rma.g(c)],null);var d=$APP.y.i(c,0,null);c=$APP.y.i(c,1,null);return pma(function(){return $APP.eF(d,$APP.qe(a)?a.o?a.o():a.call(null):a)},b,c)};Y$.s=3;var Z$=$APP.mo($APP.U1,null),sma=new $APP.h(null,2,[$APP.i3,function(){var a=new $APP.t(function(){return $APP.r$},$APP.b6,$APP.Cj([$APP.U,$APP.R,$APP.Q,$APP.Vs,$APP.wR,$APP.O,$APP.K,$APP.Us,$APP.W,$APP.X,$APP.C5],[$APP.U1,$APP.i3,"reagent/core.cljs",11,new $APP.h(null,6,[$APP.H5,!0,$APP.Lq,1,$APP.oP,1,$APP.TP,new $APP.D(null,1,5,$APP.E,[new $APP.D(null,1,5,$APP.E,[$APP.EO],null)],null),$APP.W,$APP.J(new $APP.D(null,1,5,$APP.E,[$APP.EO],null),new $APP.D(null,3,5,$APP.E,[$APP.EO,$APP.dm,$APP.n4],null)),
$APP.RV,$APP.J(null,null)],null),1,211,211,$APP.J(new $APP.D(null,1,5,$APP.E,[$APP.EO],null),new $APP.D(null,3,5,$APP.E,[$APP.EO,$APP.dm,$APP.n4],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.l($APP.r$)?$APP.r$.l:null])),b=$APP.lc(a);a=$APP.te(a);var c=Z$.m(null),d=$APP.R.g(a);$APP.I.h($APP.m.g(c),$APP.m.g(d));c=new $APP.h(null,4,[$APP.U,Z$,$APP.R,d,$APP.W,$APP.W.g(a),$APP.X,$APP.X.g(a)],
null);return $APP.l($APP.Ao.g(a))?$APP.RB(d,b,c):$APP.l($APP.Xo.g(a))?$APP.SB(d,b,c):new $APP.Io(b,d,c)}(),$APP.f6,function(){var a=new $APP.t(function(){return $APP.l$},$APP.DV,$APP.Cj([$APP.U,$APP.R,$APP.Q,$APP.Vs,$APP.wR,$APP.O,$APP.K,$APP.Us,$APP.W,$APP.X,$APP.C5],[$APP.U1,$APP.f6,"reagent/core.cljs",17,new $APP.h(null,6,[$APP.H5,!1,$APP.Lq,2,$APP.oP,2,$APP.TP,new $APP.D(null,2,5,$APP.E,[new $APP.D(null,1,5,$APP.E,[$APP.L5],null),new $APP.D(null,2,5,$APP.E,[$APP.L5,$APP.X1],null)],null),$APP.W,
$APP.J(new $APP.D(null,1,5,$APP.E,[$APP.L5],null),new $APP.D(null,2,5,$APP.E,[$APP.L5,$APP.X1],null)),$APP.RV,$APP.J(null,null)],null),1,46,46,$APP.J(new $APP.D(null,1,5,$APP.E,[$APP.L5],null),new $APP.D(null,2,5,$APP.E,[$APP.L5,$APP.X1],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.l($APP.l$)?$APP.l$.l:null])),b=$APP.lc(a);a=$APP.te(a);var c=Z$.m(null),d=$APP.R.g(a);$APP.I.h($APP.m.g(c),$APP.m.g(d));c=new $APP.h(null,4,[$APP.U,
Z$,$APP.R,d,$APP.W,$APP.W.g(a),$APP.X,$APP.X.g(a)],null);return $APP.l($APP.Ao.g(a))?$APP.RB(d,b,c):$APP.l($APP.Xo.g(a))?$APP.SB(d,b,c):new $APP.Io(b,d,c)}()],null),$$=$APP.mo(X$,null),tma=new $APP.h(null,1,[$APP.g5,function(){var a=new $APP.t(function(){return Y$},qma,$APP.Cj([$APP.U,$APP.R,$APP.Q,$APP.Vs,$APP.wR,$APP.O,$APP.K,$APP.Us,$APP.W,$APP.X,$APP.C5],[X$,$APP.g5,"reagent/dom.cljs",13,new $APP.h(null,6,[$APP.H5,!1,$APP.Lq,3,$APP.oP,3,$APP.TP,new $APP.D(null,2,5,$APP.E,[new $APP.D(null,2,5,
$APP.E,[$APP.U6,V$],null),new $APP.D(null,3,5,$APP.E,[$APP.U6,V$,W$],null)],null),$APP.W,$APP.J(new $APP.D(null,2,5,$APP.E,[$APP.U6,V$],null),new $APP.D(null,3,5,$APP.E,[$APP.U6,V$,W$],null)),$APP.RV,$APP.J(null,null)],null),1,29,29,$APP.J(new $APP.D(null,2,5,$APP.E,[$APP.U6,V$],null),new $APP.D(null,3,5,$APP.E,[$APP.U6,V$,W$],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",
$APP.l(Y$)?Y$.l:null])),b=$APP.lc(a);a=$APP.te(a);var c=$$.m(null),d=$APP.R.g(a);$APP.I.h($APP.m.g(c),$APP.m.g(d));c=new $APP.h(null,4,[$APP.U,$$,$APP.R,d,$APP.W,$APP.W.g(a),$APP.X,$APP.X.g(a)],null);return $APP.l($APP.Ao.g(a))?$APP.RB(d,b,c):$APP.l($APP.Xo.g(a))?$APP.SB(d,b,c):new $APP.Io(b,d,c)}()],null);
$APP.nl.i($APP.mC,function(a,b){var c=$APP.eh(b);b=$APP.Xe.h(c,$APP.px);var d=$APP.Xe.h(c,$APP.np),e=$APP.Xe.h(c,$APP.$o),f=$APP.Xe.h(c,$APP.Fv),k=$APP.Xe.h(c,$APP.x3),p=$APP.Xe.h(c,$APP.Gq),u=$APP.Xe.h(c,$APP.eq),n=$APP.Xe.h(c,$APP.Aq),z=$APP.Xe.h(c,$APP.Gr),C=$APP.Xe.h(c,$APP.tr),F=$APP.Xe.h(c,$APP.rr),M=$APP.Xe.h(c,$APP.cs),T=$APP.Xe.h(c,$APP.q6);c=$APP.dp.g(a);$APP.Py(c,e,F,d,u,z);d=$APP.On.j($APP.ee([$APP.P3.g(a),T]));e=$APP.NB(d);u=$APP.G.j;z=$APP.St.g(a);return u.call($APP.G,new $APP.h(null,
5,[$APP.$o,$APP.jh,$APP.dp,c,$APP.px,b,$APP.Fv,f,$APP.St,$APP.l(z)?z:$APP.l(n)?n:M],null),$APP.Aq,$APP.l(n)?$APP.MB($APP.Aq.g(a),$APP.ee([n])):null,$APP.ee([$APP.cs,$APP.l(M)?$APP.MB($APP.cs.g(a),$APP.ee([M])):null,$APP.tr,C,$APP.x3,k,$APP.Gq,p,$APP.Bq,$APP.Bq.g(e),$APP.P3,d,$APP.dq,$APP.dq.g(e)]))},new $APP.h(null,1,[$APP.np,new $APP.h(null,2,[$APP.U1,sma,X$,tma],null)],null));
}).call(this);