(function(){
shadow$provide[0]=function(b,c,a,d){a.exports=React};
shadow$provide[1]=function(b,c,a,d){a.exports=ReactDOM};
'use strict';var w9=function(a,b){let c,d;for(let e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(let f=0;f<v9.length;f++)c=v9[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},z9=function(a,b){var c=oja[a];if(void 0!==c)return c;try{x9.push(a);var d=y9[a],e=shadow$provide[a];if(void 0===d){if(void 0===e)throw"Module not provided: "+a;d={exports:{}};y9[a]=d}if(e){delete shadow$provide[a];try{e.call(d,$APP.ba,z9,d,d.exports)}catch(k){throw console.warn("shadow-cljs - failed to load",
a),k;}if(b){var f=b.globals;if(f)for(a=0;a<f.length;a++)window[f[a]]=d.exports}}}finally{x9.pop()}return d.exports},A9=function(a){return 2>$APP.Yd(a)?$APP.Sm(a):[$APP.Sm($APP.vk.i(a,0,1)),$APP.vk.h(a,1)].join("")},C9=function(a){if("string"===typeof a)return a;a=$APP.fk(a);var b=$APP.Ym.h(a,/-/),c=$APP.v(b);b=$APP.w(c);c=$APP.x(c);return $APP.l(B9.g?B9.g(b):B9.call(null,b))?a:$APP.ah.i($APP.m,b,$APP.Gk.h(A9,c))},D9=function(a){var b=function(){var c=function(){var d=$APP.oe(a);if(d){d=a.displayName;
if($APP.l(d))return d;d=a.name;return"string"===typeof d&&$APP.v(d)?d:null}return d}();if($APP.l(c))return c;c=function(){var d=null!=a?a.M&4096||$APP.qd===a.Pd?!0:!1:!1;return d?$APP.fk(a):d}();if($APP.l(c))return c;c=$APP.re(a);return $APP.Be(c)?$APP.S.g(c):null}();return $APP.l(b)?$APP.Qm($APP.m.g(b),"$","."):null},E9=function(a){return a instanceof $APP.ug||a instanceof $APP.q},F9=function(a){if($APP.Be(a))try{var b=$APP.Ve.h(a,$APP.$C)}catch(c){b=null}else b=null;return b},G9=function(a){var b=
$APP.$C.g($APP.re(a));if($APP.l(b))return b;b=F9($APP.y.i(a,1,null));if($APP.l(b))return b;b=$APP.y.i(a,0,null);switch(b instanceof $APP.ug?b.ga:null){case "\x3e":case "f\x3e":return F9($APP.y.i(a,2,null));case "r\x3e":return a=$APP.y.i(a,2,null),null==a?null:a.key;default:return null}},H9=function(a){return setTimeout(a,16)},pja=function(a,b){return a.de-b.de},I9=function(){return null},J9=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.o?d.o():d.call(null);c+=1}else return null},K9=function(a,
b,c){b.push(c);return a.schedule()},L9=function(){this.Dd=!1},N9=function(a){if($APP.l(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return M9.queue_render(a)},O9=function(a){if(null!=a&&null!=a.tf)a=a.id;else{var b=O9[$APP.da(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=O9._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.kb("Compiler.get-id",a);}return a},P9=function(a,b){if(null!=a&&null!=a.Me)a=a.Me(a,b);else{var c=P9[$APP.da(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,
a,b);else if(c=P9._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.kb("Compiler.as-element",a);}return a},Q9=function(a,b,c,d,e){if(null!=a&&null!=a.Ne)a=a.Ne(a,b,c,d,e);else{var f=Q9[$APP.da(null==a?null:a)];if(null!=f)a=f.I?f.I(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=Q9._,null!=f)a=f.I?f.I(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.kb("Compiler.make-element",a);}return a},S9=function(a,b){b.Jd=null;a:{var c=R9;R9=b;try{var d=a.o?a.o():a.call(null);break a}finally{R9=c}d=void 0}a=
b.Jd;b.oc=!1;a:{c=b.zc;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var k=f===e;if(k){c=k;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);return d},T9=function(a){var b=R9;if(null!=b){var c=b.Jd;null==c?b.Jd=[a]:c.push(a)}},U9=function(a,b,c){a.gb=$APP.G.i(a.gb,b,c);return a.ne=null},V9=function(a,b){a.gb=$APP.On.h(a.gb,b);return a.ne=null},W9=function(a,b,c){var d=a.ne;d=null==d?a.ne=$APP.nf(function(t,n,A){t.push(n);t.push(A);return t},[],
a.gb):d;for(var e=d.length,f=0;;)if(f<e){var k=d[f],p=d[f+1];p.v?p.v(k,a,b,c):p.call(null,k,a,b,c);f=2+f}else break},X9=function(a,b,c,d){$APP.Gc(a,["#object[reagent.ratom.",$APP.m.g(c)," "].join(""));a:{c=R9;R9=null;try{var e=d;break a}finally{R9=c}e=void 0}$APP.Fk(e,a,b);return $APP.Gc(a,"]")},Y9=function(a,b,c,d){this.state=a;this.D=b;this.me=c;this.gb=d;this.C=2154201088;this.M=114690},Z9=function(a){if(null!=a&&null!=a.ie)a=a.ie(a);else{var b=Z9[$APP.da(null==a?null:a)];if(null!=b)a=b.g?b.g(a):
b.call(null,a);else if(b=Z9._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.kb("IDisposable.dispose!",a);}return a},$9=function(a,b,c,d){return a._handle_change(b,c,d)},a$=function(a){this.f=a;this.state=null;this.oc=!0;this.Ke=!1;this.Kd=this.Ob=this.gb=this.zc=null;this.C=2153807872;this.M=114690},c$=function(){for(;;){var a=b$;if(null==a)return null;b$=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}},g$=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),
d+=1;else break;c=arguments[0];var e=$APP.ch(1<b.length?new $APP.wd(b.slice(1),0,null):null);b=$APP.Ve.h(e,d$);d=$APP.Ve.h(e,e$);e=$APP.Ve.h(e,f$);c=new a$(c);c._set_opts(new $APP.h(null,3,[d$,b,e$,d,f$,e],null));return c},i$=function(a,b){var c=qja,d=h$,e=S9(a,d);null!=d.zc&&(h$=g$(null),d._set_opts(c),d.f=a,d.Ob=function(){return N9.g?N9.g(b):N9.call(null,b)},b.cljsRatom=d);return e},j$=function(a,b){var c=b.argv;if(null==c){c=$APP.F;a=a.constructor;a:for(var d=$APP.ma(b),e=d.length,f=$APP.jh,k=
0;;)if(k<e){var p=d[k];f=$APP.G.i(f,$APP.Hk.g(p),$APP.oa(b,p));k+=1}else break a;b=new $APP.C(null,2,5,c,[a,f],null)}else b=c;return b},k$=function(a){var b;if(b=$APP.oe(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.qc);return b},rja=function(a,b){for(;;){var c=a.qc,d=!0===a.ff?c.call(a,a):function(){var e=j$(a,a.props);switch($APP.Yd(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.y.h(e,1));case 3:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2));case 4:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,
2),$APP.y.h(e,3));case 5:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2),$APP.y.h(e,3),$APP.y.h(e,4));default:return c.apply(a,$APP.HG.g(e).slice(1))}}();if($APP.De(d))return P9(b,d);if($APP.Me(d))a.qc=k$(d)?function(e,f,k,p,t){return function(){function n(D){var E=null;if(0<arguments.length){E=0;for(var M=Array(arguments.length-0);E<M.length;)M[E]=arguments[E+0],++E;E=new $APP.wd(M,0,null)}return A.call(this,E)}function A(D){return P9(f,$APP.ah.i($APP.zs,t,D))}n.s=0;n.u=function(D){D=$APP.v(D);return A(D)};
n.j=A;return n}()}(a,b,c,null,d):d;else return d}},sja=function(a,b){switch(a instanceof $APP.ug?a.ga:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.y.i(f,1,null),c=$APP.Be(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.hf;d=null!=d?d:c.hf=l$.g(null);return $APP.Hh(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,
this,j$(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,this,j$(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,j$(this,c))};case "shouldComponentUpdate":return function(c){var d=m$;if($APP.l(d))return d;d=this.props.argv;var e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.Tj.h(d,e)}catch(k){return!1}}else return f?b.call(this,this,j$(this,this.props),j$(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,
d){return b.call(this,this,j$(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,d){return b.call(this,this,j$(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,j$(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.oa(this,
"cljsRatom");null!=c&&Z9(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};case "componentDidCatch":return function(c,d){return b.call(this,this,c,d)};default:return null}},uja=function(a){return $APP.nf(function(b,c,d){return $APP.G.i(b,$APP.Hk.g(tja(c)),d)},$APP.jh,a)},vja=function(a,b){var c=function(){var k=n$.g(a);return $APP.l(k)?k:o$.g(a)}(),d=null==n$.g(a),e=function(){var k=p$.g(a);if($APP.l(k))return k;k=D9(c);return $APP.l(k)?k:$APP.m.g($APP.Rn.g("reagent"))}(),f=$APP.nf(function(k,
p,t){var n=$APP.G.i,A=sja(p,t);return n.call($APP.G,k,p,$APP.l(A)?A:t)},$APP.jh,a);return $APP.G.j(f,p$,e,$APP.ce([q$,d,n$,c,o$,function(){var k=this,p=$APP.oa(k,"cljsRatom");k.cljsIsDirty=!1;return null==p?i$(function(){a:{var t=r$;r$=k;try{var n=rja(k,b);break a}finally{r$=t}n=void 0}return n},k):p._run(!1)}]))},s$=function(a){return $APP.nf(function(b,c,d){c=$APP.fk(c);b[c]=d;return b},{},a)},xja=function(a,b){return vja($APP.Nn.j($APP.ce([wja,uja(a)])),b)},x$=function(a,b){function c(p,t,n){t$.Component.call(this,
p,t,n);$APP.l(k)&&(k.h?k.h(this,p):k.call(null,this,p));$APP.l(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.de=u$+=1;return this}a=xja(a,b);b=s$($APP.ah.j($APP.On,a,p$,v$,$APP.Yp,$APP.ce([o$,n$,w$])));var d=s$($APP.Uj(a,w$)),e=p$.g(a),f=v$.g(a),k=$APP.Yp.g(a);w9(c.prototype,t$.Component.prototype,b);$APP.l(o$.g(a))&&(c.prototype.render=o$.g(a));$APP.l(n$.g(a))&&(c.prototype.qc=n$.g(a));$APP.l(q$.g(a))&&(c.prototype.ff=q$.g(a));w9(c,t$.Component,d);$APP.l(e)&&(c.displayName=e,c.Jc=e,c.be=
function(p){return $APP.Gc(p,e)});c.yd=!0;return c.prototype.constructor=c},y$=function(a,b,c){a=O9(a);return b[a]=c},yja=function(a,b){for(;;){var c=b.qc,d=b.argv,e=$APP.ah.h(c,d);if($APP.De(e))return P9(a,e);if($APP.Me(e))b.qc=k$(e)?function(f,k,p,t,n,A){return function(){function D(M){var T=null;if(0<arguments.length){T=0;for(var aa=Array(arguments.length-0);T<aa.length;)aa[T]=arguments[T+0],++T;T=new $APP.wd(aa,0,null)}return E.call(this,T)}function E(M){return P9(f,$APP.ah.i($APP.zs,A,M))}D.s=
0;D.u=function(M){M=$APP.v(M);return E(M)};D.j=E;return D}()}(a,b,c,null,d,e):e;else return e}},zja=function(a,b){var c=b.argv,d=b.qc;b=t$.useState(0);$APP.y.i(b,0,null);var e=$APP.y.i(b,1,null),f=t$.useRef();$APP.l(f.current)||function(){var p={forceUpdate:function(){return e.g?e.g($APP.Jd):e.call(null,$APP.Jd)}};p.de=u$+=1;p.constructor=d;p.qc=d;return f.current=p}();var k=f.current;b=$APP.oa(k,"cljsRatom");t$.useEffect(function(){return function(){var p=$APP.oa(k,"cljsRatom");return null==p?null:
Z9(p)}},[]);k.argv=c;k.cljsIsDirty=!1;return null==b?i$(function(){a:{var p=r$;r$=k;try{var t=yja(a,k);break a}finally{r$=p}t=void 0}return t},k):b._run(!1)},Aja=function(a,b){a=a.argv;b=b.argv;var c=!1===m$;if(c)try{return $APP.Zd.h(a,b)}catch(d){return!1}else return c},Bja=function(a,b){function c(e){return zja(a,e)}var d=$APP.oa(b,O9(a));if($APP.l(d))return d;c.displayName=D9(b);d=t$.memo(c,Aja);y$(a,b,d);return d},Eja=function(a,b,c,d){var e=$APP.ch($APP.jh);e=$APP.Ve.h(e,Cja);if(a===document.activeElement&&
$APP.Xe(Dja,a.type)&&"string"===typeof b&&"string"===typeof c){var f=a.value;if($APP.Tj.h(f,c))return M9.add_after_render(function(){return z$.g?z$.g(d):z$.call(null,d)});c=$APP.Yd(f)-a.selectionStart;c=$APP.Yd(b)-c;d.zd=b;a.value=b;$APP.oe(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.zd=b;a.value=b;return $APP.oe(e)?e.g?e.g(b):e.call(null,b):null},z$=function(a){if($APP.l(a.ce)){a.De=!1;var b=a.gf,c=a.zd,d=a.fe;return $APP.Tj.h(b,c)?Eja(d,b,c,a):null}return null},
Fja=function(a,b,c){a.zd=c.target.value;$APP.l(a.De)||(a.De=!0,M9.add_after_render(function(){return z$(a)}));return b.g?b.g(c):b.call(null,c)},Gja=function(a){var b=r$;if($APP.l(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.l(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.l(b.ce)||(b.ce=!0,b.zd=c);$APP.l(b.Oe)||(b.Oe=$APP.oe(e)?function(f){b.fe=f;return e.g?e.g(f):e.call(null,f)}:$APP.l($APP.l(e)?e.hasOwnProperty("current"):
e)?function(f){b.fe=f;return e.current=f}:function(f){return b.fe=f});b.gf=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return Fja(b,d,f)};a.ref=b.Oe}},A$=function(a,b){return a.hasOwnProperty(b)?$APP.oa(a,b):null},Hja=function(a,b,c){if(E9(b)){var d=A$(B$,$APP.fk(b));null==d?(d=C9(b),b=$APP.fk(b),b=B$[b]=d):b=d}c=C$.g?C$.g(c):C$.call(null,c);a[b]=c;return a},C$=function(a){return"object"!==$APP.da(a)?a:E9(a)?$APP.fk(a):$APP.Be(a)?$APP.nf(Hja,{},a):$APP.we(a)?$APP.Up(a):$APP.Me(a)?function(){function b(d){var e=
null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.wd(f,0,null)}return c.call(this,e)}function c(d){return $APP.ah.h(a,d)}b.s=0;b.u=function(d){d=$APP.v(d);return c(d)};b.j=c;return b}():$APP.Up(a)},Ija=function(a,b,c){if(E9(b)){var d=A$(D$,$APP.fk(b));null==d?(d=C9(b),b=$APP.fk(b),b=D$[b]=d):b=d}c=C$(c);a[b]=c;return a},Jja=function(a){return"object"!==$APP.da(a)?a:E9(a)?$APP.fk(a):$APP.Be(a)?$APP.nf(Ija,{},a):$APP.we(a)?$APP.Up(a):
$APP.Me(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.wd(f,0,null)}return c.call(this,e)}function c(d){return $APP.ah.h(a,d)}b.s=0;b.u=function(d){d=$APP.v(d);return c(d)};b.j=c;return b}():$APP.Up(a)},Kja=function(a,b,c,d,e){switch($APP.Yd(b)-e){case 0:return t$.createElement(c,d);case 1:return t$.createElement(c,d,P9(a,$APP.y.i(b,e,null)));default:return t$.createElement.apply(null,$APP.nf(function(f,
k,p){k>=e&&f.push(P9(a,p));return f},[c,d],b))}},E$=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.jf=d},G$=function(a,b,c){var d=$APP.oa(a,O9(c));null==d?k$(a)?a=y$(c,a,a):(d=$APP.re(a),d=$APP.G.i(d,F$,a),d=x$(d,c),a=y$(c,a,d)):a=d;c={};c.argv=b;b=G9(b);null!=b&&(c.key=b);return t$.createElement(a,c)},H$=function(a,b,c,d){var e={};e.qc=a;e.argv=$APP.Wm.h(b,c);b=G9(b);null!=b&&(e.key=b);return t$.createElement(Bja(d,a),e)},Lja=function(a,b,c){var d;if(d=$APP.oe(a))d=null==a?null:a.prototype,
d=null!=(null==d?null:d.render);return d?G$(a,b,c):H$(a,b,1,c)},J$=function(a,b,c,d){var e=a.tag,f=$APP.y.i(b,c,null),k=null==f||$APP.Be(f),p=function(){var n=k?f:null;var A=$APP.qq.g(n);A=$APP.l(A)?$APP.G.i(n,$APP.qq,I$.g(A)):n;var D=a.id;n=a.className;D=null!=D&&null==$APP.cp.g(A)?$APP.G.i(A,$APP.cp,D):A;if($APP.l(n)){var E=$APP.G.i,M=I$.h,T=$APP.qq.g(A);A=$APP.l(T)?T:Mja.g(A);n=E.call($APP.G,D,$APP.qq,M.call(I$,n,A))}else n=D;n=$APP.l(a.jf)?Jja(n):C$(n);return $APP.l(n)?n:{}}();c+=k?1:0;a:switch(e){case "input":case "textarea":var t=
!0;break a;default:t=!1}if(t)return t=function(){var n=d.uf;if($APP.l(n))return n;n=x$(Nja,d);return d.uf=n}(),P9(d,$APP.qe(new $APP.C(null,6,5,$APP.F,[t,b,e,p,c,d],null),$APP.re(b)));t=F9($APP.re(b));null!=t&&(p.key=t);return Q9(d,b,e,p,c)},Oja=function(a,b){return $APP.HG.g($APP.Gk.h(function(c){return P9(b,c)},a))},Qja=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.gl.j($APP.ce([a])));var d=$APP.y.i(a,0,null);switch(d instanceof $APP.ug?d.ga:null){case "\x3e":return c=$APP.y.i(a,1,null),
c=new E$(c,null,null,null),J$(c,a,2,b);case "r\x3e":c=$APP.y.i(a,1,null);d=$APP.y.i(a,2,null);d=$APP.l(d)?d:{};var e=F9($APP.re(a));null!=e&&(d.key=e);return Q9(b,a,c,d,3);case "f\x3e":return H$($APP.y.i(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.y.i(a,1,null),c=null==d||$APP.Be(d),d=C$(c?d:null),d=$APP.l(d)?d:{},c=1+(c?1:0),e=G9(a),null!=e&&(d.key=e),Q9(b,a,t$.Fragment,d,c);default:if(E9(d)||"string"===typeof d)a:for(;;)switch(c=$APP.y.i(a,0,null),c=$APP.fk(c),d=c.indexOf("\x3e"),d){case -1:d=
A$(K$,c);if(null==d){var f=$APP.x($APP.rk(Pja,$APP.fk(c)));d=$APP.y.i(f,0,null);e=$APP.y.i(f,1,null);f=$APP.y.i(f,2,null);f=null==f?null:$APP.Qm(f,/\./," ");var k=$APP.Tj.h(-1,d.indexOf("-"));d=new E$(d,e,f,k);c=K$[c]=d}else c=d;b=J$(c,a,1,b);break a;case 0:b=null;break a;default:a=$APP.qe(new $APP.C(null,2,5,$APP.F,[$APP.vk.i(c,0,d),$APP.G.i($APP.qe(a,null),0,$APP.vk.h(c,d+1))],null),$APP.re(a))}else b=c.i?c.i(d,a,b):c.call(null,d,a,b);return b}},Tja=function(a,b,c){var d=m$;m$=!0;try{return Rja.render(a.o?
a.o():a.call(null),b,function(){var e=m$;m$=!1;try{return $APP.ll.v(Sja,$APP.G,b,a),M9.flush_after_render(),null!=c?c.o?c.o():c.call(null):null}finally{m$=e}})}finally{m$=d}},v9="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),v$=new $APP.ug(null,"getInitialState","getInitialState",1541760916),Uja=new $APP.ug(null,"component-will-unmount","component-will-unmount",-2058314698),n$=new $APP.ug(null,"reagentRender","reagentRender",-358306383),
L$=new $APP.q(null,"container","container",-96406180,null),Vja=new $APP.q("reagent.core","as-element","reagent.core/as-element",-1369748434,null),Wja=new $APP.ug(null,"contextType","contextType",1033066077),Xja=new $APP.ug(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739),Yja=new $APP.ug(null,"display-name","display-name",694513143),Mja=new $APP.ug(null,"className","className",-1983287057),Zja=new $APP.q("reagent.dom","render","reagent.dom/render",-1216356973,null),M$=new $APP.q(null,
"callback-or-compiler","callback-or-compiler",90200066,null),N$=new $APP.q(null,"reagent.core","reagent.core",1841519592,null),O$=new $APP.q(null,"compiler","compiler",1372604796,null),f$=new $APP.ug(null,"on-dispose","on-dispose",2105306360),P$=new $APP.ug(null,"no-cache","no-cache",1588056370),$ja=new $APP.ug(null,"function-components","function-components",1492814963),Q$=new $APP.q(null,"reagent.dom","reagent.dom",-2138920962,null),aka=new $APP.ug(null,"callback","callback",-705136228),q$=new $APP.ug(null,
"cljsLegacyRender","cljsLegacyRender",-1527295613),Cja=new $APP.ug(null,"on-write","on-write",31519475),bka=new $APP.ug(null,"contextTypes","contextTypes",-2023853910),R$=new $APP.q(null,"render","render",232498073,null),o$=new $APP.ug(null,"render","render",-1408033454),d$=new $APP.ug(null,"auto-run","auto-run",1958400437),cka=new $APP.ug(null,"childContextTypes","childContextTypes",578717991),F$=new $APP.ug(null,"reagent-render","reagent-render",-985383853),dka=new $APP.q("reagent.core","atom",
"reagent.core/atom",1748890217,null),eka=new $APP.ug(null,"componentWillUnmount","componentWillUnmount",1573788814),S$=new $APP.q(null,"as-element","as-element",-2139409597,null),p$=new $APP.ug(null,"displayName","displayName",-809144601),fka=new $APP.ug(null,"getDerivedStateFromError","getDerivedStateFromError",166658477),e$=new $APP.ug(null,"on-set","on-set",-140953470),gka=new $APP.ug(null,"component-did-update","component-did-update",-1468549173),hka=new $APP.ug(null,"shouldComponentUpdate","shouldComponentUpdate",
1795750960);var y9={},oja={},x9=[];z9.cache={};z9.resolve=function(a){return a};var t$=z9(0,{});var ika={};$APP.kl.g(null);var jka={},kka="undefined"!==typeof window&&null!=window.document,B9=new $APP.Wj(null,new $APP.h(null,2,["aria",null,"data",null],null),null),I$=function I$(a){switch(arguments.length){case 0:return I$.o();case 1:return I$.g(arguments[0]);case 2:return I$.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return I$.j(arguments[0],arguments[1],new $APP.wd(c.slice(2),0,null))}};I$.o=function(){return null};
I$.g=function(a){return $APP.we(a)?(a=$APP.rB.h(function(b){return $APP.l(b)?E9(b)?$APP.fk(b):b:null},a),$APP.v(a)?$APP.Dr.h(" ",a):null):E9(a)?$APP.fk(a):a};I$.h=function(a,b){return $APP.l(a)?$APP.l(b)?[$APP.m.g(I$.g(a))," ",$APP.m.g(I$.g(b))].join(""):I$.g(a):I$.g(b)};I$.j=function(a,b,c){return $APP.ff.i(I$,I$.h(a,b),c)};I$.u=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);c=$APP.x(c);return this.j(b,a,c)};I$.s=2;var m$=!1;var u$=0,T$=kka?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.l(b))return b;b=a.webkitRequestAnimationFrame;if($APP.l(b))return b;b=a.mozRequestAnimationFrame;if($APP.l(b))return b;b=a.msRequestAnimationFrame;return $APP.l(b)?b:H9}().bind(a)}():H9;$APP.g=L9.prototype;$APP.g.flush_after_render=function(){var a=this.pd;if(null==a)return null;this.pd=null;return J9(a)};$APP.g.queue_render=function(a){null==this.Bd&&(this.Bd=[]);return K9(this,this.Bd,a)};
$APP.g.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.Dd)return null;this.Dd=!0;return T$.g?T$.g(a):T$.call(null,a)};$APP.g.flush_before_flush=function(){var a=this.qd;if(null==a)return null;this.qd=null;return J9(a)};$APP.g.flush_queues=function(){this.flush_before_flush();I9();this.flush_render();return this.flush_after_render()};$APP.g.run_queues=function(){this.Dd=!1;return this.flush_queues()};
$APP.g.add_before_flush=function(a){null==this.qd&&(this.qd=[]);return K9(this,this.qd,a)};$APP.g.add_after_render=function(a){null==this.pd&&(this.pd=[]);return K9(this,this.pd,a)};$APP.g.flush_render=function(){var a=this.Bd;if(null==a)return null;this.Bd=null;a:{a.sort(pja);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};var M9=new L9;var R9;$APP.kl.g(0);var b$=null;$APP.g=Y9.prototype;$APP.g.S=function(a,b,c){return X9(b,c,"RAtom",new $APP.h(null,1,[$APP.UH,this.bb(null)],null))};$APP.g.V=function(){return this.D};$APP.g.X=function(){return $APP.ha(this)};$APP.g.T=function(a,b){return this===b};$APP.g.Cb=function(a,b){a=this.state;this.state=b;null!=this.gb&&W9(this,a,b);return b};$APP.g.Vd=function(a,b){return this.Cb(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.g.Wd=function(a,b,c){return this.Cb(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.g.Xd=function(a,b,c,d){return this.Cb(null,b.i?b.i(this.state,c,d):b.call(null,this.state,c,d))};$APP.g.Yd=function(a,b,c,d,e){return this.Cb(null,$APP.ah.I(b,this.state,c,d,e))};$APP.g.$d=function(a,b){W9(this,a,b)};$APP.g.wd=function(a,b,c){return U9(this,b,c)};$APP.g.xd=function(a,b){return V9(this,b)};$APP.g.Z=function(a,b){return new Y9(this.state,b,this.me,this.gb)};
$APP.g.bb=function(){T9(this);return this.state};var l$=function l$(a){switch(arguments.length){case 1:return l$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l$.j(arguments[0],new $APP.wd(c.slice(1),0,null))}};l$.g=function(a){return new Y9(a,null,null,null)};l$.j=function(a,b){var c=$APP.ch(b);b=$APP.Ve.h(c,$APP.ya);c=$APP.Ve.h(c,$APP.nH);return new Y9(a,b,c,null)};l$.u=function(a){var b=$APP.w(a);a=$APP.x(a);return this.j(b,a)};
l$.s=1;$APP.g=a$.prototype;$APP.g._peek_at=function(){var a=R9;R9=null;try{return this.bb(null)}finally{R9=a}};$APP.g._handle_change=function(a,b,c){return b===c||this.oc?null:null==this.Ob?(this.oc=!0,null==b$&&(b$=[],!1===M9.Dd&&M9.schedule()),b$.push(this)):!0===this.Ob?this._run(!1):this.Ob.g?this.Ob.g(this):this.Ob.call(null,this)};
$APP.g._update_watching=function(a){var b=$APP.dk(a),c=$APP.dk(this.zc);this.zc=a;a=$APP.v($APP.l7.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var k=d.U(null,f);$APP.Kc(k,this,$9);f+=1}else if(a=$APP.v(a))d=a,$APP.Ee(d)?(a=$APP.Wc(d),f=$APP.Xc(d),d=a,e=$APP.Yd(a),a=f):(a=$APP.w(d),$APP.Kc(a,this,$9),a=$APP.x(d),d=null,e=0),f=0;else break;b=$APP.v($APP.l7.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.U(null,e),$APP.Mc(a,this),e+=1;else if(b=$APP.v(b))c=b,$APP.Ee(c)?(b=$APP.Wc(c),d=$APP.Xc(c),c=b,a=$APP.Yd(b),
b=d,d=a):(a=$APP.w(c),$APP.Mc(a,this),b=$APP.x(c),c=null,d=0),e=0;else return null};$APP.g._queued_run=function(){return this.oc&&null!=this.zc?this._run(!0):null};$APP.g._try_capture=function(a){try{return this.Kd=null,S9(a,this)}catch(b){return this.Kd=this.state=a=b,this.oc=!1}};$APP.g._run=function(a){var b=this.state;a=$APP.l(a)?this._try_capture(this.f):S9(this.f,this);this.Ke||(this.state=a,null==this.gb||$APP.Zd.h(b,a)||W9(this,b,a));return a};
$APP.g._set_opts=function(a){var b=$APP.ch(a);a=$APP.Ve.h(b,d$);var c=$APP.Ve.h(b,e$),d=$APP.Ve.h(b,f$);b=$APP.Ve.h(b,P$);null!=a&&(this.Ob=a);null!=c&&(this.qf=c);null!=d&&(this.Le=d);return null!=b?this.Ke=b:null};$APP.g.S=function(a,b,c){return X9(b,c,"Reaction",new $APP.h(null,1,[$APP.UH,this.bb(null)],null))};$APP.g.X=function(){return $APP.ha(this)};$APP.g.T=function(a,b){return this===b};
$APP.g.ie=function(){var a=this.state,b=this.zc;this.Ob=this.state=this.zc=null;this.oc=!0;b=$APP.v($APP.dk(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);$APP.Mc(f,this);e+=1}else if(b=$APP.v(b))c=b,$APP.Ee(c)?(b=$APP.Wc(c),e=$APP.Xc(c),c=b,d=$APP.Yd(b),b=e):(b=$APP.w(c),$APP.Mc(b,this),b=$APP.x(c),c=null,d=0),e=0;else break;null!=this.Le&&this.Le(a);a=this.Tf;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};
$APP.g.Cb=function(a,b){a=this.state;this.state=b;this.qf(a,b);W9(this,a,b);return b};$APP.g.Vd=function(a,b){a=this.Cb;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.g.Wd=function(a,b,c){a=this.Cb;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Xd=function(a,b,c,d){a=this.Cb;var e=this._peek_at();b=b.i?b.i(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.g.Yd=function(a,b,c,d,e){return this.Cb(null,$APP.ah.I(b,this._peek_at(),c,d,e))};$APP.g.$d=function(a,b){W9(this,a,b)};$APP.g.wd=function(a,b,c){return U9(this,b,c)};$APP.g.xd=function(a,b){a=$APP.ve(this.gb);V9(this,b);return!a&&$APP.ve(this.gb)&&null==this.Ob?this.ie(null):null};
$APP.g.bb=function(){var a=this.Kd;if(null!=a)throw a;(a=null==R9)&&(c$.o?c$.o():c$.call(null));a&&null==this.Ob?this.oc&&(a=this.state,this.state=this.f.o?this.f.o():this.f.call(null),null==this.gb||$APP.Zd.h(a,this.state)||W9(this,a,this.state)):(T9(this),this.oc&&this._run(!1));return this.state};I9=c$;var h$=g$(null);var r$,qja=new $APP.h(null,1,[P$,!0],null),wja=new $APP.h(null,2,[hka,null,eka,null],null),tja=function(a){var b=$APP.kl.g($APP.jh);return function(c){var d=$APP.Ve.h($APP.jc(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.ll.v(b,$APP.G,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.fk(a);a=$APP.Qm(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.Ym.h(a,/-/);var b=$APP.v(a);a=$APP.w(b);b=$APP.x(b);return $APP.ah.i($APP.m,a,$APP.Gk.h(A9,b))}),w$=new $APP.C(null,5,5,$APP.F,[cka,
bka,Wja,Xja,fka],null);var Dja=new $APP.Wj(null,new $APP.h(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),Nja=new $APP.h(null,4,[Yja,"ReagentInput",gka,z$,Uja,function(a){return a.ce=null},F$,function(a,b,c,d,e){Gja(c);return Q9(e,a,b,c,d)}],null);var lka={},U$,Pja=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,B$={"class":"className","for":"htmlFor",charset:"charSet"},D$={},K$={},V$=function(a){var b=$APP.Rn.o(),c=$APP.l($ja.g(a))?Lja:G$;if("undefined"===typeof ika||"undefined"===typeof jka||"undefined"===typeof lka||"undefined"===typeof U$)U$=function(d,e,f,k){this.rf=d;this.id=e;this.He=f;this.nf=k;this.C=393216;this.M=0},U$.prototype.Z=function(d,e){return new U$(this.rf,this.id,this.He,e)},U$.prototype.V=function(){return this.nf},U$.prototype.tf=
function(){return this.id},U$.prototype.Me=function(d,e){return"object"!==$APP.da(e)?e:$APP.De(e)?Qja(e,this,this.He):$APP.Je(e)?Oja(e,this):E9(e)?$APP.fk(e):(null!=e?e.C&2147483648||$APP.qd===e.da||(e.C?0:$APP.$a($APP.Hc,e)):$APP.$a($APP.Hc,e))?$APP.gl.j($APP.ce([e])):e},U$.prototype.Ne=function(d,e,f,k,p){return Kja(this,e,f,k,p)},U$.yd=!0,U$.Jc="reagent.impl.template/t_reagent$impl$template36985",U$.be=function(d){return $APP.Gc(d,"reagent.impl.template/t_reagent$impl$template36985")};return new U$(a,
b,c,$APP.jh)}($APP.jh);var W$=function W$(a){switch(arguments.length){case 1:return W$.g(arguments[0]);case 2:return W$.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};W$.g=function(a){return P9(V$,a)};W$.h=function(a,b){return P9(b,a)};W$.s=2;
var X$=function X$(a){switch(arguments.length){case 1:return X$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X$.j(arguments[0],new $APP.wd(c.slice(1),0,null))}};X$.g=function(a){return l$.g(a)};X$.j=function(a,b){return $APP.ah.i(l$,a,b)};X$.u=function(a){var b=$APP.w(a);a=$APP.x(a);return this.j(b,a)};X$.s=1;var Rja=z9(1,{});var Sja=$APP.kl.g($APP.jh),Y$=function Y$(a){switch(arguments.length){case 2:return Y$.h(arguments[0],arguments[1]);case 3:return Y$.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};Y$.h=function(a,b){return Y$.i(a,b,V$)};
Y$.i=function(a,b,c){c$();c=$APP.oe(c)?new $APP.C(null,2,5,$APP.F,[V$,c],null):new $APP.C(null,2,5,$APP.F,[c,aka.g(c)],null);var d=$APP.y.i(c,0,null);c=$APP.y.i(c,1,null);return Tja(function(){return P9(d,$APP.oe(a)?a.o?a.o():a.call(null):a)},b,c)};Y$.s=3;var Z$=$APP.ko(N$,null),mka=new $APP.h(null,2,[$APP.f2,function(){var a=new $APP.u(function(){return X$},dka,$APP.Aj([$APP.V,$APP.S,$APP.Q,$APP.Ts,$APP.CO,$APP.O,$APP.K,$APP.Ss,$APP.X,$APP.Y,$APP.x4],[N$,$APP.f2,"reagent/core.cljs",11,new $APP.h(null,6,[$APP.B4,!0,$APP.Jq,1,$APP.AM,1,$APP.dN,new $APP.C(null,1,5,$APP.F,[new $APP.C(null,1,5,$APP.F,[$APP.RL],null)],null),$APP.X,$APP.J(new $APP.C(null,1,5,$APP.F,[$APP.RL],null),new $APP.C(null,3,5,$APP.F,[$APP.RL,$APP.bm,$APP.k3],null)),$APP.FS,$APP.J(null,
null)],null),1,211,211,$APP.J(new $APP.C(null,1,5,$APP.F,[$APP.RL],null),new $APP.C(null,3,5,$APP.F,[$APP.RL,$APP.bm,$APP.k3],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.l(X$)?X$.l:null])),b=$APP.jc(a);a=$APP.re(a);var c=Z$.m(null),d=$APP.S.g(a);$APP.I.h($APP.m.g(c),$APP.m.g(d));c=new $APP.h(null,4,[$APP.V,Z$,$APP.S,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.l($APP.yo.g(a))?
$APP.PB(d,b,c):$APP.l($APP.Vo.g(a))?$APP.QB(d,b,c):new $APP.Go(b,d,c)}(),S$,function(){var a=new $APP.u(function(){return W$},Vja,$APP.Aj([$APP.V,$APP.S,$APP.Q,$APP.Ts,$APP.CO,$APP.O,$APP.K,$APP.Ss,$APP.X,$APP.Y,$APP.x4],[N$,S$,"reagent/core.cljs",17,new $APP.h(null,6,[$APP.B4,!1,$APP.Jq,2,$APP.AM,2,$APP.dN,new $APP.C(null,2,5,$APP.F,[new $APP.C(null,1,5,$APP.F,[$APP.F4],null),new $APP.C(null,2,5,$APP.F,[$APP.F4,O$],null)],null),$APP.X,$APP.J(new $APP.C(null,1,5,$APP.F,[$APP.F4],null),new $APP.C(null,
2,5,$APP.F,[$APP.F4,O$],null)),$APP.FS,$APP.J(null,null)],null),1,46,46,$APP.J(new $APP.C(null,1,5,$APP.F,[$APP.F4],null),new $APP.C(null,2,5,$APP.F,[$APP.F4,O$],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.l(W$)?W$.l:null])),b=$APP.jc(a);a=$APP.re(a);var c=Z$.m(null),d=$APP.S.g(a);$APP.I.h($APP.m.g(c),$APP.m.g(d));c=new $APP.h(null,4,[$APP.V,Z$,$APP.S,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.l($APP.yo.g(a))?
$APP.PB(d,b,c):$APP.l($APP.Vo.g(a))?$APP.QB(d,b,c):new $APP.Go(b,d,c)}()],null),$$=$APP.ko(Q$,null),nka=new $APP.h(null,1,[R$,function(){var a=new $APP.u(function(){return Y$},Zja,$APP.Aj([$APP.V,$APP.S,$APP.Q,$APP.Ts,$APP.CO,$APP.O,$APP.K,$APP.Ss,$APP.X,$APP.Y,$APP.x4],[Q$,R$,"reagent/dom.cljs",13,new $APP.h(null,6,[$APP.B4,!1,$APP.Jq,3,$APP.AM,3,$APP.dN,new $APP.C(null,2,5,$APP.F,[new $APP.C(null,2,5,$APP.F,[$APP.N5,L$],null),new $APP.C(null,3,5,$APP.F,[$APP.N5,L$,M$],null)],null),$APP.X,$APP.J(new $APP.C(null,
2,5,$APP.F,[$APP.N5,L$],null),new $APP.C(null,3,5,$APP.F,[$APP.N5,L$,M$],null)),$APP.FS,$APP.J(null,null)],null),1,29,29,$APP.J(new $APP.C(null,2,5,$APP.F,[$APP.N5,L$],null),new $APP.C(null,3,5,$APP.F,[$APP.N5,L$,M$],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",
$APP.l(Y$)?Y$.l:null])),b=$APP.jc(a);a=$APP.re(a);var c=$$.m(null),d=$APP.S.g(a);$APP.I.h($APP.m.g(c),$APP.m.g(d));c=new $APP.h(null,4,[$APP.V,$$,$APP.S,d,$APP.X,$APP.X.g(a),$APP.Y,$APP.Y.g(a)],null);return $APP.l($APP.yo.g(a))?$APP.PB(d,b,c):$APP.l($APP.Vo.g(a))?$APP.QB(d,b,c):new $APP.Go(b,d,c)}()],null);
$APP.ll.i($APP.kC,function(a,b){var c=$APP.ch(b);b=$APP.Ve.h(c,$APP.nx);var d=$APP.Ve.h(c,$APP.np),e=$APP.Ve.h(c,$APP.Yo),f=$APP.Ve.h(c,$APP.Dv),k=$APP.Ve.h(c,$APP.v2),p=$APP.Ve.h(c,$APP.Eq),t=$APP.Ve.h(c,$APP.cq),n=$APP.Ve.h(c,$APP.yq),A=$APP.Ve.h(c,$APP.Er),D=$APP.Ve.h(c,$APP.tr),E=$APP.Ve.h(c,$APP.rr),M=$APP.Ve.h(c,$APP.as),T=$APP.Ve.h(c,$APP.j5);c=$APP.bp.g(a);$APP.JB(c,e,E,d,t,A);d=$APP.Nn.j($APP.ce([$APP.M2.g(a),T]));e=$APP.LB(d);t=$APP.G.j;A=$APP.Qt.g(a);return t.call($APP.G,new $APP.h(null,
5,[$APP.Yo,$APP.jh,$APP.bp,c,$APP.nx,b,$APP.Dv,f,$APP.Qt,$APP.l(A)?A:$APP.l(n)?n:M],null),$APP.yq,$APP.l(n)?$APP.KB($APP.yq.g(a),$APP.ce([n])):null,$APP.ce([$APP.as,$APP.l(M)?$APP.KB($APP.as.g(a),$APP.ce([M])):null,$APP.tr,D,$APP.v2,k,$APP.Eq,p,$APP.zq,$APP.zq.g(e),$APP.M2,d,$APP.bq,$APP.bq.g(e)]))},new $APP.h(null,1,[$APP.np,new $APP.h(null,2,[N$,mka,Q$,nka],null)],null));
}).call(this);